import type { Properties as DataGridProperties } from 'devextreme/ui/data_grid';
import type { Properties as FilterBuilderProperties } from 'devextreme/ui/filter_builder';

export type WidgetName =
  'dxAccordion'
  | 'dxActionSheet'
  | 'dxAutocomplete'
  | 'dxButton'
  | 'dxButtonGroup'
  | 'dxCalendar'
  | 'dxCalendarView'
  | 'dxCardView'
  | 'dxChart'
  | 'dxChat'
  | 'dxCheckBox'
  | 'dxColorBox'
  | 'dxContextMenu'
  | 'dxDataGrid'
  | 'dxDateBox'
  | 'dxDateRangeBox'
  | 'dxDrawer'
  | 'dxDropDownBox'
  | 'dxDropDownButton'
  | 'dxDropDownMenu'
  | 'dxDraggable'
  | 'dxFileManager'
  | 'dxFileUploader'
  | 'dxFilterBuilder'
  | 'dxForm'
  | 'dxGallery'
  | 'dxHtmlEditor'
  | 'dxList'
  | 'dxLoadIndicator'
  | 'dxLoadPanel'
  | 'dxLookup'
  | 'dxMap'
  | 'dxMenu'
  | 'dxMultiView'
  | 'dxNumberBox'
  | 'dxOverlay'
  | 'dxPager'
  | 'dxPivotGrid'
  | 'dxPivotGridFieldChooser'
  | 'dxPopover'
  | 'dxPopup'
  | 'dxProgressBar'
  | 'dxRadioGroup'
  | 'dxRangeSlider'
  | 'dxScheduler'
  | 'dxScrollable'
  | 'dxScrollView'
  | 'dxSelectBox'
  | 'dxSlider'
  | 'dxSortable'
  | 'dxSpeedDialAction'
  | 'dxSplitter'
  | 'dxSwitch'
  | 'dxTabPanel'
  | 'dxTabs'
  | 'dxTagBox'
  | 'dxTextArea'
  | 'dxTextBox'
  | 'dxTileView'
  | 'dxToast'
  | 'dxToolbar'
  | 'dxTooltip'
  | 'dxTreeList'
  | 'dxTreeView'
  | 'dxValidationSummary'
  | 'dxValidator';

export interface WidgetOptions {
  dxDataGrid: DataGridProperties;
  dxFilterBuilder: FilterBuilderProperties;
  // TODO: write other widgets
}
