name: Chrome headless shell installer
description: Install chrome-headless-shell

# Chrome headless shell
# https://developer.chrome.com/blog/chrome-headless-shell

inputs:
  chrome-version:
    description: Chrome headless shell version to install
    default: "latest"

runs:
  using: composite
  steps:
    - name: Setup chrome-headless-shell
      shell: bash
      env:
        CHROME_VERSION: ${{ inputs.chrome-version }}
      run: |
        if [ -n "$CHROME_VERSION" ]; then
          echo "version to install: $CHROME_VERSION"
          PUPPETEER_CMD="browsers install chrome-headless-shell@$CHROME_VERSION"
          CHROME_BIN=`pnpm --filter devextreme-angular exec puppeteer $PUPPETEER_CMD | awk '{print $2}'`
          echo "chrome-headless-shell installed in: $CHROME_BIN"
          chmod +x $CHROME_BIN
          $CHROME_BIN --version
          echo "CHROME_SHELL=$CHROME_BIN" >> $GITHUB_ENV
        else
          echo "chrome-headless-shell not installed!"
        fi
        
