import CleanCSS, { Options, OptionsPromise } from 'clean-css';
import AutoPrefix from 'autoprefixer';
import PostCss from 'postcss';
import commonOptions from '../data/clean-css-options.json';

import { browsersList } from '../data/metadata/dx-theme-builder-metadata';

export function addBasePath(css: string | Buffer, basePath: string): string {
  const normalizedPath = `${basePath.replace(/[/\\]$/, '')}/`;
  return css.toString().replace(/(url\()("|')?(icons|fonts)/g, `$1$2${normalizedPath}$3`);
}

function buildThemeBuilderInfoHeader(version: string): string {
  const generatedBy = '* Generated by the DevExpress ThemeBuilder';
  const versionString = `* Version: ${version}`;
  const link = '* http://js.devexpress.com/ThemeBuilder/';

  return `/*${generatedBy}\n${versionString}\n${link}\n*/\n\n`;
}

export function addInfoHeader(
  css: string | Buffer,
  version: string,
  appendInfoHeaderAfterBody = false,
): string {
  const header = buildThemeBuilderInfoHeader(version);
  const source = css.toString();
  const encoding = '@charset "UTF-8";';

  // clean-css may emit @charset immediately followed by :root / @import with no newline.
  const charsetPrefix = /^@charset\s+"utf-8";\s*/i;
  const match = source.match(charsetPrefix);
  if (match) {
    const rest = source.slice(match[0].length).trimStart();

    if (appendInfoHeaderAfterBody) {
      const joined = `${encoding.trimEnd()}${rest}`.replace(
        /^(@charset\s+"utf-8";)\s+/i,
        '$1',
      );
      return `${joined}\n${header}`;
    }
    return `${encoding}\n${header}${rest}`;
  }
  return `${header}${source}`;
}

export async function cleanCss(css: string): Promise<string> {
  const promiseOptions: Options = { returnPromise: true };
  const options = { ...commonOptions, ...promiseOptions };
  const cleaner = new CleanCSS(options as OptionsPromise);
  return (await cleaner.minify(css)).styles;
}

export async function autoPrefix(css: string): Promise<string> {
  return (await PostCss(AutoPrefix({
    overrideBrowserslist: browsersList,
  })).process(css, {
    from: undefined,
  })).css;
}

// eslint-disable-next-line @stylistic/max-len
export function fixSwatchCss(css: string | Buffer, swatchClass: string, colorScheme: string): string {
  let result = css.toString();

  const escapedSelector = swatchClass.replace('.', '\\.');

  const swatchOrderRegex = new RegExp(`([ \\t]*)([\\w\\.#:\\*][\\w\\.#:\\*\\->()\\s]*)(${escapedSelector}\\s)([^,{+~]*)`, 'gm');
  const changeTypographyRulesOrderRegex = /(\.dx-swatch-.*?)\s(\.dx-theme-.*?-typography)(.*?)(\s{|,)/g;
  const themeMarkerRegex = /(\.dx-theme-marker\s*{\s*font-family:\s*['"]dx\..*?\.)(.*)(['"])/g;

  result = result
    .replace(swatchOrderRegex, '$1$3$2$4')
    .replace(changeTypographyRulesOrderRegex, '$2 $1$3,$2$1$3$4')
    .replace(themeMarkerRegex, `$1${colorScheme}$3`);

  return result;
}

export function removeExternalResources(css: string): string {
  const fontRegex = /^\s*@import\surl\(.*googleapis.*\);[\n\r]{0,2}/gmi;
  return css.replace(fontRegex, '');
}

export function optimizeCss(css: string): string {
  const optimizedCss = css.replace(/rgba\(0,0,0,0\)/g, 'transparent');
  return optimizedCss;
}
