// deprecated
export {
    getElementBoxParams,
    getSize,
    parseHeight,
    addOffsetToMaxHeight,
    addOffsetToMinHeight,
    getVerticalOffsets,
    getVisibleHeight,
    implementationsMap,
    getWidth,
    setWidth,
    getHeight,
    setHeight,
    getOuterWidth,
    setOuterWidth,
    getOuterHeight,
    setOuterHeight,
    getInnerWidth,
    setInnerWidth,
    getInnerHeight,
    setInnerHeight,
    getWindowByElement,
    getOffset,
} from '../../__internal/core/utils/m_size';
