version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    reviewers:
      - "DevExpress/devextreme-core"
    labels:
      - "dependencies"
