version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'npm'
    directory: '/themebuilder-scss/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
