export const defaultToolbarItems = [
    { name: 'bold' },
    { name: 'italic' },
    { name: 'underline' },
    { name: 'separator' },
    { name: 'undo' },
    { name: 'redo' },
  ];
  
  export const fullToolbarItems = [
    { name: 'undo' },
    { name: 'redo' },
    { name: 'separator' },
    {
      name: 'size',
      acceptedValues: ['8pt', '10pt', '12pt', '14pt', '18pt', '24pt', '36pt'],
      options: { placeholder: 'Font size' },
    },
    {
      name: 'font',
      acceptedValues: ['Arial', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Tahoma', 'Times New Roman', 'Verdana'],
      options: { placeholder: 'Font' },
    },
    { name: 'separator' },
    { name: 'bold' },
    { name: 'italic' },
    { name: 'strike' },
    { name: 'underline' },
    { name: 'separator' },
    { name: 'alignLeft' },
    { name: 'alignCenter' },
    { name: 'alignRight' },
    { name: 'alignJustify' },
    { name: 'separator' },
    { name: 'orderedList' },
    { name: 'bulletList' },
    { name: 'separator' },
    {
      name: 'header',
      acceptedValues: [false, 1, 2, 3, 4, 5],
      options: { placeholder: 'Header' },
    },
    { name: 'separator' },
    { name: 'color' },
    { name: 'background' },
    { name: 'separator' },
    { name: 'link' },
    { name: 'image' },
    { name: 'separator' },
    { name: 'clear' },
    { name: 'codeBlock' },
    { name: 'blockquote' },
    { name: 'separator' },
    { name: 'insertTable' },
    { name: 'deleteTable' },
    { name: 'insertRowAbove' },
    { name: 'insertRowBelow' },
    { name: 'deleteRow' },
    { name: 'insertColumnLeft' },
    { name: 'insertColumnRight' },
    { name: 'deleteColumn' },
  ];
