export {
  DashStyle,
  HatchDirection,
  HorizontalEdge,
  LabelPosition,
  Palette,
  PaletteExtensionMode,
  TextOverflow,
  ShiftLabelOverlap,
  WordWrap,
  FunnelAlgorithm,
  LegendItem,
  DisposingEvent,
  DrawnEvent,
  ExportedEvent,
  ExportingEvent,
  FileSavingEvent,
  HoverChangedEvent,
  IncidentOccurredEvent,
  InitializedEvent,
  ItemClickEvent,
  LegendClickEvent,
  OptionChangedEvent,
  SelectionChangedEvent,
  Item,
  Properties,
} from './funnel';
