# https://github.com/drone/drone/

clone:
  git:
    image: plugins/git
    depth: 50
    when:
      event: [ push, tag ]

  git-pr:
    image: devexpress/devextreme-build-git-pr
    when:
      event: [ pull_request ]

pipeline:

  build:
    image: devexpress/devextreme-build:20_1
    commands:
      - ./drone-cache.sh restore
      - ./docker-ci.sh
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: ts }
    - { TARGET: test, CONSTEL: export }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
    - { TARGET: test, PERF: true, JQUERY: true, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.editors, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.grid }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.scheduler }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: viz }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: export }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: misc }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.editors }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.grid }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.scheduler }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: viz }
    - { TARGET: test_functional, COMPONENT: dataGrid }
    - { TARGET: test_functional, COMPONENT: scheduler }
    - { TARGET: test_functional, COMPONENT: editors }
    - { TARGET: test_functional, COMPONENT: navigation }
    - { TARGET: test_themebuilder }
