# https://github.com/drone/drone/

clone:
  git:
    image: plugins/git
    depth: 50
    when:
      event: [ push, tag ]

  git-pr:
    image: devexpress/devextreme-build-git-pr
    when:
      event: [ pull_request ]

pipeline:

  build:
    image: devexpress/devextreme-build:19_1
    environment:
      - HEADLESS=true
      - TRAVIS=true      
    commands:
      - ./drone-cache.sh restore
      - script -qefc ./docker-ci.sh /dev/null
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: ts }
    - { TARGET: test, CONSTEL: export }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: misc, JQUERY: true }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
    - { TARGET: test, BROWSER: firefox, CONSTEL: export }
    - { TARGET: test, BROWSER: firefox, CONSTEL: misc }
    - { TARGET: test, BROWSER: firefox, CONSTEL: ui }
    - { TARGET: test, BROWSER: firefox, CONSTEL: ui.editors }
    - { TARGET: test, BROWSER: firefox, CONSTEL: ui.grid }
    - { TARGET: test, BROWSER: firefox, CONSTEL: ui.scheduler }
    - { TARGET: test, BROWSER: firefox, CONSTEL: viz }
    - { TARGET: test_functional, COMPONENT: dataGrid }
    - { TARGET: test_functional, COMPONENT: scheduler }
    - { TARGET: test_functional, COMPONENT: editors }
    - { TARGET: test_functional, COMPONENT: navigation }
    - { TARGET: test_themebuilder }
