# https://github.com/drone/drone/

clone:
  git:
    image: plugins/git
    depth: 50
    when:
      event: [ push, tag ]

  git-pr:
    image: devexpress/devextreme-build-git-pr
    when:
      event: [ pull_request ]

pipeline:

  build:
    image: devexpress/devextreme-build:21_2
    environment:
      - TRAVIS=true
    commands:
      - ./drone-cache.sh restore
      - script -qefc ./docker-ci.sh /dev/null
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: ts }
