# https://github.com/drone/drone/

clone:
  git:
    image: plugins/git
    depth: 50
    when:
      event: [ push, tag ]

  git-pr:
    image: devexpress/devextreme-build-git-pr
    when:
      event: [ pull_request ]

pipeline:

  build:
    image: devexpress/devextreme-build:20_2
    environment:
      - TRAVIS=true
    commands:
      - ./drone-cache.sh restore
      - script -qefc ./docker-ci.sh /dev/null
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: ts }
    - { TARGET: test, CONSTEL: export }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: misc, TZ: 'PST8PDT' }
    - { TARGET: test, CONSTEL: misc, TZ: 'Japan' }
    - { TARGET: test, CONSTEL: misc, TZ: 'Australia/ACT' }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.widgets }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.editors, TZ: 'PST8PDT' }
    - { TARGET: test, CONSTEL: ui.editors, TZ: 'Japan' }
    - { TARGET: test, CONSTEL: ui.editors, TZ: 'Australia/ACT' }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'PST8PDT' }
    - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'Japan' }
    - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'Australia/ACT' }
    - { TARGET: test, CONSTEL: viz }
    - { TARGET: test, CONSTEL: renovation }
    - { TARGET: test, PERF: true, JQUERY: true, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.editors, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.grid, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.scheduler }
    - { TARGET: test, MOBILE_UA: ios9, CONSTEL: viz }
    - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui }
    - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.editors, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.grid, NO_HEADLESS: true }
    - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.scheduler }
    - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: viz }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: export }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: misc }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.editors }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.grid }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.scheduler }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: viz }
    - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: renovation }
    - { TARGET: test_jest }
    - { TARGET: native_components }
    - { TARGET: test_scss }
    - { TARGET: font_icons_test }
