# https://github.com/drone/drone/

clone:
  git:
    image: plugins/git
    depth: 50
    when:
      event: [ push, tag ]

  git-pr:
    image: devexpress/devextreme-build-git-pr
    when:
      event: [ pull_request ]

pipeline:

  build:
    image: devexpress/devextreme-build:21_1
    environment:
      - TRAVIS=true
    commands:
      - ./drone-cache.sh restore
      - script -qefc ./docker-ci.sh /dev/null
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: ts }
    - { TARGET: test, CONSTEL: export }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.widgets }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
    - { TARGET: test, CONSTEL: renovation }
    - { TARGET: test, PERF: true, JQUERY: true, NO_HEADLESS: true }
    - { TARGET: test_styles }
