# https://github.com/drone/drone/

pipeline:

  build:
    image: devexpress/devextreme-build:17_1
    pull: true
    commands:
      - ./drone-cache.sh restore
      - ./docker-ci.sh
      - ./drone-cache.sh rebuild

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
