# Install: http://readme.drone.io/0.5/install/cli/
# Docs: http://readme.drone.io/0.5/
# Local run: drone exec --matrix TARGET=test

pipeline:

  clone:
    image: plugins/git

  build:
    image: devexpress/devextreme-build:17_2
    pull: true
    commands: ./docker-ci.sh

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
