# https://github.com/drone/drone/

pipeline:

  cache-restore:
    image: devexpress/devextreme-ci-cache
    restore: true
    when:
      event: [ push, pull_request ]

  build:
    image: devexpress/devextreme-build:17_2
    pull: true
    commands:
      - ./drone-pr-workaround.sh
      - ./docker-ci.sh

  cache-rebuild:
    image: devexpress/devextreme-ci-cache
    rebuild: true
    secrets: [ devextreme_ci_cache_access_key, devextreme_ci_cache_secret_key ]
    when:
      event: [ push ]

matrix:
  include:
    - { TARGET: lint }
    - { TARGET: test, CONSTEL: misc }
    - { TARGET: test, CONSTEL: ui }
    - { TARGET: test, CONSTEL: ui.editors }
    - { TARGET: test, CONSTEL: ui.grid }
    - { TARGET: test, CONSTEL: ui.scheduler }
    - { TARGET: test, CONSTEL: viz }
