export const Themes = {
  genericLight: 'generic.light',
  genericDark: 'generic.dark',
  genericCarmine: 'generic.carmine',
  genericSoftBlue: 'generic.softblue',
  genericDarkMoon: 'generic.darkmoon',
  genericDarkViolet: 'generic.darkviolet',
  genericGreenMist: 'generic.greenmist',
  genericContrast: 'generic.contrast',
  genericLightCompact: 'generic.light.compact',
  genericDarkCompact: 'generic.dark.compact',
  genericCarmineCompact: 'generic.carmine.compact',
  genericSoftBlueCompact: 'generic.softblue.compact',
  genericDarkMoonCompact: 'generic.darkmoon.compact',
  genericDarkVioletCompact: 'generic.darkviolet.compact',
  genericGreenMistCompact: 'generic.greenmist.compact',
  genericContrastCompact: 'generic.contrast.compact',
  materialBlue: 'material.blue.light',
  materialBlueDark: 'material.blue.dark',
  materialLime: 'material.lime.light',
  materialLimeDark: 'material.lime.dark',
  materialOrange: 'material.orange.light',
  materialOrangeDark: 'material.orange.dark',
  materialPurple: 'material.purple.light',
  materialPurpleDark: 'material.purple.dark',
  materialTeal: 'material.teal.light',
  materialTealDark: 'material.teal.dark',
  materialBlueCompact: 'material.blue.light.compact',
  materialBlueDarkCompact: 'material.blue.dark.compact',
  materialLimeCompact: 'material.lime.light.compact',
  materialLimeDarkCompact: 'material.lime.dark.compact',
  materialOrangeCompact: 'material.orange.light.compact',
  materialOrangeDarkCompact: 'material.orange.dark.compact',
  materialPurpleCompact: 'material.purple.light.compact',
  materialPurpleDarkCompact: 'material.purple.dark.compact',
  materialTealCompact: 'material.teal.light.compact',
  materialTealDarkCompact: 'material.teal.dark.compact',
  fluentBlue: 'fluent.blue.light',
  fluentBlueDark: 'fluent.blue.dark',
  // eslint-disable-next-line spellcheck/spell-checker
  fluentSaaS: 'fluent.saas.light',
  // eslint-disable-next-line spellcheck/spell-checker
  fluentSaaSDark: 'fluent.saas.dark',
};
