name: 'Build DevExtreme npm package'
runs:
  using: "composite"
  steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./mode_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Install packages in devextreme repo
      run: npm install --no-audit --no-fund

    - name: Restore artifacts cache
      uses: actions/cache@v2
      with:
        path: ./artifacts
        key: build-npm-devextreme-artifacts-${{ github.sha }}

    - name: Build devextreme repo
      run: test -d artifacts || npm run build-npm-devextreme
