export {
  ContentReadyEvent,
  DisposingEvent,
  InitializedEvent,
  ItemClickEvent,
  ItemContextMenuEvent,
  ItemHoldEvent,
  ItemRenderedEvent,
  OptionChangedEvent,
  SelectionChangedEvent,
  TitleClickEvent,
  TitleHoldEvent,
  TitleRenderedEvent,
  dxTabPanelOptions,
  Item,
  Properties,
} from './tab_panel';
