import './common';
import './common/grids';
import './common/charts';
import * as CommonModule from './common/index';
import * as AiIntegrationModule from './common/ai-integration';
import * as ChartsModule from './common/charts';
import * as CoreAnimationModule from './common/core/animation';
import * as CoreEnvironmentModule from './common/core/environment';
import * as CoreEventsModule from './common/core/events';
import * as CoreLocalizationModule from './common/core/localization';
import * as DataModule from './common/data';
import * as ExportExcelModule from './common/export/excel';
import * as ExportPdfModule from './common/export/pdf';

export * from 'devextreme-angular/core';
export * from './ui/all';

export { DxAccordionComponent, DxAccordionModule } from 'devextreme-angular/ui/accordion';
export { DxActionSheetComponent, DxActionSheetModule } from 'devextreme-angular/ui/action-sheet';
export { DxAutocompleteComponent, DxAutocompleteModule } from 'devextreme-angular/ui/autocomplete';
export { DxBarGaugeComponent, DxBarGaugeModule } from 'devextreme-angular/ui/bar-gauge';
export { DxBoxComponent, DxBoxModule } from 'devextreme-angular/ui/box';
export { DxBulletComponent, DxBulletModule } from 'devextreme-angular/ui/bullet';
export { DxButtonComponent, DxButtonModule } from 'devextreme-angular/ui/button';
export { DxButtonGroupComponent, DxButtonGroupModule } from 'devextreme-angular/ui/button-group';
export { DxCalendarComponent, DxCalendarModule } from 'devextreme-angular/ui/calendar';
export { DxCardViewComponent, DxCardViewModule } from 'devextreme-angular/ui/card-view';
export { DxChartComponent, DxChartModule } from 'devextreme-angular/ui/chart';
export { DxChatComponent, DxChatModule } from 'devextreme-angular/ui/chat';
export { DxCheckBoxComponent, DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
export { DxCircularGaugeComponent, DxCircularGaugeModule } from 'devextreme-angular/ui/circular-gauge';
export { DxColorBoxComponent, DxColorBoxModule } from 'devextreme-angular/ui/color-box';
export { DxContextMenuComponent, DxContextMenuModule } from 'devextreme-angular/ui/context-menu';
export { DxDataGridComponent, DxDataGridModule } from 'devextreme-angular/ui/data-grid';
export { DxDateBoxComponent, DxDateBoxModule } from 'devextreme-angular/ui/date-box';
export { DxDateRangeBoxComponent, DxDateRangeBoxModule } from 'devextreme-angular/ui/date-range-box';
export { DxDiagramComponent, DxDiagramModule } from 'devextreme-angular/ui/diagram';
export { DxDraggableComponent, DxDraggableModule } from 'devextreme-angular/ui/draggable';
export { DxDrawerComponent, DxDrawerModule } from 'devextreme-angular/ui/drawer';
export { DxDropDownBoxComponent, DxDropDownBoxModule } from 'devextreme-angular/ui/drop-down-box';
export { DxDropDownButtonComponent, DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';
export { DxFileManagerComponent, DxFileManagerModule } from 'devextreme-angular/ui/file-manager';
export { DxFileUploaderComponent, DxFileUploaderModule } from 'devextreme-angular/ui/file-uploader';
export { DxFilterBuilderComponent, DxFilterBuilderModule } from 'devextreme-angular/ui/filter-builder';
export { DxFormComponent, DxFormModule } from 'devextreme-angular/ui/form';
export { DxFunnelComponent, DxFunnelModule } from 'devextreme-angular/ui/funnel';
export { DxGalleryComponent, DxGalleryModule } from 'devextreme-angular/ui/gallery';
export { DxGanttComponent, DxGanttModule } from 'devextreme-angular/ui/gantt';
export { DxHtmlEditorComponent, DxHtmlEditorModule } from 'devextreme-angular/ui/html-editor';
export { DxLinearGaugeComponent, DxLinearGaugeModule } from 'devextreme-angular/ui/linear-gauge';
export { DxListComponent, DxListModule } from 'devextreme-angular/ui/list';
export { DxLoadIndicatorComponent, DxLoadIndicatorModule } from 'devextreme-angular/ui/load-indicator';
export { DxLoadPanelComponent, DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
export { DxLookupComponent, DxLookupModule } from 'devextreme-angular/ui/lookup';
export { DxMapComponent, DxMapModule } from 'devextreme-angular/ui/map';
export { DxMenuComponent, DxMenuModule } from 'devextreme-angular/ui/menu';
export { DxMultiViewComponent, DxMultiViewModule } from 'devextreme-angular/ui/multi-view';
export { DxNumberBoxComponent, DxNumberBoxModule } from 'devextreme-angular/ui/number-box';
export { DxPaginationComponent, DxPaginationModule } from 'devextreme-angular/ui/pagination';
export { DxPieChartComponent, DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
export { DxPivotGridComponent, DxPivotGridModule } from 'devextreme-angular/ui/pivot-grid';
export { DxPivotGridFieldChooserComponent, DxPivotGridFieldChooserModule } from 'devextreme-angular/ui/pivot-grid-field-chooser';
export { DxPolarChartComponent, DxPolarChartModule } from 'devextreme-angular/ui/polar-chart';
export { DxPopoverComponent, DxPopoverModule } from 'devextreme-angular/ui/popover';
export { DxPopupComponent, DxPopupModule } from 'devextreme-angular/ui/popup';
export { DxProgressBarComponent, DxProgressBarModule } from 'devextreme-angular/ui/progress-bar';
export { DxRadioGroupComponent, DxRadioGroupModule } from 'devextreme-angular/ui/radio-group';
export { DxRangeSelectorComponent, DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
export { DxRangeSliderComponent, DxRangeSliderModule } from 'devextreme-angular/ui/range-slider';
export { DxResizableComponent, DxResizableModule } from 'devextreme-angular/ui/resizable';
export { DxResponsiveBoxComponent, DxResponsiveBoxModule } from 'devextreme-angular/ui/responsive-box';
export { DxSankeyComponent, DxSankeyModule } from 'devextreme-angular/ui/sankey';
export { DxSchedulerComponent, DxSchedulerModule } from 'devextreme-angular/ui/scheduler';
export { DxScrollViewComponent, DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
export { DxSelectBoxComponent, DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
export { DxSliderComponent, DxSliderModule } from 'devextreme-angular/ui/slider';
export { DxSortableComponent, DxSortableModule } from 'devextreme-angular/ui/sortable';
export { DxSparklineComponent, DxSparklineModule } from 'devextreme-angular/ui/sparkline';
export { DxSpeechToTextComponent, DxSpeechToTextModule } from 'devextreme-angular/ui/speech-to-text';
export { DxSpeedDialActionComponent, DxSpeedDialActionModule } from 'devextreme-angular/ui/speed-dial-action';
export { DxSplitterComponent, DxSplitterModule } from 'devextreme-angular/ui/splitter';
export { DxStepperComponent, DxStepperModule } from 'devextreme-angular/ui/stepper';
export { DxSwitchComponent, DxSwitchModule } from 'devextreme-angular/ui/switch';
export { DxTabPanelComponent, DxTabPanelModule } from 'devextreme-angular/ui/tab-panel';
export { DxTabsComponent, DxTabsModule } from 'devextreme-angular/ui/tabs';
export { DxTagBoxComponent, DxTagBoxModule } from 'devextreme-angular/ui/tag-box';
export { DxTextAreaComponent, DxTextAreaModule } from 'devextreme-angular/ui/text-area';
export { DxTextBoxComponent, DxTextBoxModule } from 'devextreme-angular/ui/text-box';
export { DxTileViewComponent, DxTileViewModule } from 'devextreme-angular/ui/tile-view';
export { DxToastComponent, DxToastModule } from 'devextreme-angular/ui/toast';
export { DxToolbarComponent, DxToolbarModule } from 'devextreme-angular/ui/toolbar';
export { DxTooltipComponent, DxTooltipModule } from 'devextreme-angular/ui/tooltip';
export { DxTreeListComponent, DxTreeListModule } from 'devextreme-angular/ui/tree-list';
export { DxTreeMapComponent, DxTreeMapModule } from 'devextreme-angular/ui/tree-map';
export { DxTreeViewComponent, DxTreeViewModule } from 'devextreme-angular/ui/tree-view';
export { DxValidationGroupComponent, DxValidationGroupModule } from 'devextreme-angular/ui/validation-group';
export { DxValidationSummaryComponent, DxValidationSummaryModule } from 'devextreme-angular/ui/validation-summary';
export { DxValidatorComponent, DxValidatorModule } from 'devextreme-angular/ui/validator';
export { DxVectorMapComponent, DxVectorMapModule } from 'devextreme-angular/ui/vector-map';
export namespace Common {
    export type ApplyValueMode = import('devextreme/common').ApplyValueMode;
    export type AsyncRule = import('devextreme/common').AsyncRule;
    export type ButtonStyle = import('devextreme/common').ButtonStyle;
    export type ButtonType = import('devextreme/common').ButtonType;
    export type CompareRule = import('devextreme/common').CompareRule;
    export type ComparisonOperator = import('devextreme/common').ComparisonOperator;
    export const config = (CommonModule as any).config as typeof import('devextreme/common').config;
    export type CustomRule = import('devextreme/common').CustomRule;
    export type DataStructure = import('devextreme/common').DataStructure;
    export type DataType = import('devextreme/common').DataType;
    export type DateLike = import('devextreme/common').DateLike;
    export type DayOfWeek = import('devextreme/common').DayOfWeek;
    export type DefaultOptionsRule<T> = import('devextreme/common').DefaultOptionsRule<T>;
    export type Direction = import('devextreme/common').Direction;
    export type DisplayMode = import('devextreme/common').DisplayMode;
    export type DragDirection = import('devextreme/common').DragDirection;
    export type Draggable = import('devextreme/common').Draggable;
    export type DragHighlight = import('devextreme/common').DragHighlight;
    export type EditorStyle = import('devextreme/common').EditorStyle;
    export type EmailRule = import('devextreme/common').EmailRule;
    export type ExportFormat = import('devextreme/common').ExportFormat;
    export type FieldChooserLayout = import('devextreme/common').FieldChooserLayout;
    export type FirstDayOfWeek = import('devextreme/common').FirstDayOfWeek;
    export type FloatingActionButtonDirection = import('devextreme/common').FloatingActionButtonDirection;
    export type Format = import('devextreme/common').Format;
    export type GlobalConfig = import('devextreme/common').GlobalConfig;
    export const Guid = (CommonModule as any).Guid as typeof import('devextreme/common').Guid;
    export type Guid = import('devextreme/common').Guid;
    export type HorizontalAlignment = import('devextreme/common').HorizontalAlignment;
    export type HorizontalEdge = import('devextreme/common').HorizontalEdge;
    export type LabelMode = import('devextreme/common').LabelMode;
    export type MaskMode = import('devextreme/common').MaskMode;
    export type Mode = import('devextreme/common').Mode;
    export type NumericRule = import('devextreme/common').NumericRule;
    export type Orientation = import('devextreme/common').Orientation;
    export type PageLoadMode = import('devextreme/common').PageLoadMode;
    export type PageOrientation = import('devextreme/common').PageOrientation;
    export type PatternRule = import('devextreme/common').PatternRule;
    export type Position = import('devextreme/common').Position;
    export type PositionAlignment = import('devextreme/common').PositionAlignment;
    export type RangeRule = import('devextreme/common').RangeRule;
    export type RequiredRule = import('devextreme/common').RequiredRule;
    export type Scrollable = import('devextreme/common').Scrollable;
    export type ScrollbarMode = import('devextreme/common').ScrollbarMode;
    export type ScrollDirection = import('devextreme/common').ScrollDirection;
    export type ScrollMode = import('devextreme/common').ScrollMode;
    export type SearchMode = import('devextreme/common').SearchMode;
    export type SelectAllMode = import('devextreme/common').SelectAllMode;
    export const setTemplateEngine = (CommonModule as any).setTemplateEngine as typeof import('devextreme/common').setTemplateEngine;
    export type SimplifiedSearchMode = import('devextreme/common').SimplifiedSearchMode;
    export type SingleMultipleAllOrNone = import('devextreme/common').SingleMultipleAllOrNone;
    export type SingleMultipleOrNone = import('devextreme/common').SingleMultipleOrNone;
    export type SingleOrMultiple = import('devextreme/common').SingleOrMultiple;
    export type SingleOrNone = import('devextreme/common').SingleOrNone;
    export type SliderValueChangeMode = import('devextreme/common').SliderValueChangeMode;
    export type Sortable = import('devextreme/common').Sortable;
    export type SortOrder = import('devextreme/common').SortOrder;
    export type StoreType = import('devextreme/common').StoreType;
    export type StringLengthRule = import('devextreme/common').StringLengthRule;
    export type SubmenuShowMode = import('devextreme/common').SubmenuShowMode;
    export type TabsIconPosition = import('devextreme/common').TabsIconPosition;
    export type TabsStyle = import('devextreme/common').TabsStyle;
    export type template = import('devextreme/common').template;
    export type TextBoxPredefinedButton = import('devextreme/common').TextBoxPredefinedButton;
    export type TextEditorButton = import('devextreme/common').TextEditorButton;
    export type TextEditorButtonLocation = import('devextreme/common').TextEditorButtonLocation;
    export type ToolbarItemComponent = import('devextreme/common').ToolbarItemComponent;
    export type ToolbarItemLocation = import('devextreme/common').ToolbarItemLocation;
    export type TooltipShowMode = import('devextreme/common').TooltipShowMode;
    export type ValidationCallbackData = import('devextreme/common').ValidationCallbackData;
    export type ValidationMessageMode = import('devextreme/common').ValidationMessageMode;
    export type ValidationRule = import('devextreme/common').ValidationRule;
    export type ValidationRuleType = import('devextreme/common').ValidationRuleType;
    export type ValidationStatus = import('devextreme/common').ValidationStatus;
    export type VerticalAlignment = import('devextreme/common').VerticalAlignment;
    export type VerticalEdge = import('devextreme/common').VerticalEdge;
    export namespace AiIntegration {
        export const AIIntegration = (AiIntegrationModule as any).AIIntegration as typeof import('devextreme/common/ai-integration').AIIntegration;
        export type AIIntegration = import('devextreme/common/ai-integration').AIIntegration;
        export type AIIntegrationOptions = import('devextreme/common/ai-integration').AIIntegrationOptions;
        export type AIProvider = import('devextreme/common/ai-integration').AIProvider;
        export type AIResponse = import('devextreme/common/ai-integration').AIResponse;
        export type ExecuteGridAssistantCommandResponse = import('devextreme/common/ai-integration').ExecuteGridAssistantCommandResponse;
        export type GenerateGridColumnCommandResponse = import('devextreme/common/ai-integration').GenerateGridColumnCommandResponse;
        export type Prompt = import('devextreme/common/ai-integration').Prompt;
        export type RequestParams = import('devextreme/common/ai-integration').RequestParams;
        export type RequestParamsData = import('devextreme/common/ai-integration').RequestParamsData;
        export type Response = import('devextreme/common/ai-integration').Response;
    }
    export namespace Charts {
        export type AnimationEaseMode = import('devextreme/common/charts').AnimationEaseMode;
        export type AnnotationType = import('devextreme/common/charts').AnnotationType;
        export type ArgumentAxisHoverMode = import('devextreme/common/charts').ArgumentAxisHoverMode;
        export type AxisScaleType = import('devextreme/common/charts').AxisScaleType;
        export type ChartsAxisLabelOverlap = import('devextreme/common/charts').ChartsAxisLabelOverlap;
        export type ChartsColor = import('devextreme/common/charts').ChartsColor;
        export type ChartsDataType = import('devextreme/common/charts').ChartsDataType;
        export type ChartsLabelOverlap = import('devextreme/common/charts').ChartsLabelOverlap;
        export type DashStyle = import('devextreme/common/charts').DashStyle;
        export type DiscreteAxisDivisionMode = import('devextreme/common/charts').DiscreteAxisDivisionMode;
        export type Font = import('devextreme/common/charts').Font;
        export type GradientColor = import('devextreme/common/charts').GradientColor;
        export type HatchDirection = import('devextreme/common/charts').HatchDirection;
        export type LabelOverlap = import('devextreme/common/charts').LabelOverlap;
        export type LabelPosition = import('devextreme/common/charts').LabelPosition;
        export type LegendHoverMode = import('devextreme/common/charts').LegendHoverMode;
        export type LegendItem = import('devextreme/common/charts').LegendItem;
        export type LegendMarkerState = import('devextreme/common/charts').LegendMarkerState;
        export type Palette = import('devextreme/common/charts').Palette;
        export type PaletteColorSet = import('devextreme/common/charts').PaletteColorSet;
        export type PaletteExtensionMode = import('devextreme/common/charts').PaletteExtensionMode;
        export type PointInteractionMode = import('devextreme/common/charts').PointInteractionMode;
        export type PointSymbol = import('devextreme/common/charts').PointSymbol;
        export const registerGradient = (ChartsModule as any).registerGradient as typeof import('devextreme/common/charts').registerGradient;
        export const registerPattern = (ChartsModule as any).registerPattern as typeof import('devextreme/common/charts').registerPattern;
        export type RelativePosition = import('devextreme/common/charts').RelativePosition;
        export type ScaleBreak = import('devextreme/common/charts').ScaleBreak;
        export type ScaleBreakLineStyle = import('devextreme/common/charts').ScaleBreakLineStyle;
        export type SeriesHoverMode = import('devextreme/common/charts').SeriesHoverMode;
        export type SeriesLabel = import('devextreme/common/charts').SeriesLabel;
        export type SeriesPoint = import('devextreme/common/charts').SeriesPoint;
        export type SeriesSelectionMode = import('devextreme/common/charts').SeriesSelectionMode;
        export type SeriesType = import('devextreme/common/charts').SeriesType;
        export type ShiftLabelOverlap = import('devextreme/common/charts').ShiftLabelOverlap;
        export type TextOverflow = import('devextreme/common/charts').TextOverflow;
        export type Theme = import('devextreme/common/charts').Theme;
        export type TimeInterval = import('devextreme/common/charts').TimeInterval;
        export type TimeIntervalConfig = import('devextreme/common/charts').TimeIntervalConfig;
        export type ValueAxisVisualRangeUpdateMode = import('devextreme/common/charts').ValueAxisVisualRangeUpdateMode;
        export type ValueErrorBarDisplayMode = import('devextreme/common/charts').ValueErrorBarDisplayMode;
        export type ValueErrorBarType = import('devextreme/common/charts').ValueErrorBarType;
        export type VisualRange = import('devextreme/common/charts').VisualRange;
        export type VisualRangeUpdateMode = import('devextreme/common/charts').VisualRangeUpdateMode;
        export type WordWrap = import('devextreme/common/charts').WordWrap;
        export type ZoomPanAction = import('devextreme/common/charts').ZoomPanAction;
    }
    export namespace Core {
        export namespace Animation {
            export type AnimationConfig = import('devextreme/common/core/animation').AnimationConfig;
            export const animationPresets = (CoreAnimationModule as any).animationPresets as typeof import('devextreme/common/core/animation').animationPresets;
            export type AnimationState = import('devextreme/common/core/animation').AnimationState;
            export const cancelAnimationFrame = (CoreAnimationModule as any).cancelAnimationFrame as typeof import('devextreme/common/core/animation').cancelAnimationFrame;
            export type CollisionResolution = import('devextreme/common/core/animation').CollisionResolution;
            export type CollisionResolutionCombination = import('devextreme/common/core/animation').CollisionResolutionCombination;
            export const fx = (CoreAnimationModule as any).fx as typeof import('devextreme/common/core/animation').fx;
            export type PositionConfig = import('devextreme/common/core/animation').PositionConfig;
            export const requestAnimationFrame = (CoreAnimationModule as any).requestAnimationFrame as typeof import('devextreme/common/core/animation').requestAnimationFrame;
            export const TransitionExecutor = (CoreAnimationModule as any).TransitionExecutor as typeof import('devextreme/common/core/animation').TransitionExecutor;
            export type TransitionExecutor = import('devextreme/common/core/animation').TransitionExecutor;
        }
        export namespace Environment {
            export type Device = import('devextreme/common/core/environment').Device;
            export const getTimeZones = (CoreEnvironmentModule as any).getTimeZones as typeof import('devextreme/common/core/environment').getTimeZones;
            export const hideTopOverlay = (CoreEnvironmentModule as any).hideTopOverlay as typeof import('devextreme/common/core/environment').hideTopOverlay;
            export const initMobileViewport = (CoreEnvironmentModule as any).initMobileViewport as typeof import('devextreme/common/core/environment').initMobileViewport;
            export type SchedulerTimeZone = import('devextreme/common/core/environment').SchedulerTimeZone;
        }
        export namespace Events {
            export type AsyncCancelable = import('devextreme/common/core/events').AsyncCancelable;
            export type Cancelable = import('devextreme/common/core/events').Cancelable;
            export type ChangedOptionInfo = import('devextreme/common/core/events').ChangedOptionInfo;
            export type EventInfo<TComponent> = import('devextreme/common/core/events').EventInfo<TComponent>;
            export type EventObject = import('devextreme/common/core/events').EventObject;
            export type InitializedEventInfo<TComponent> = import('devextreme/common/core/events').InitializedEventInfo<TComponent>;
            export type ItemInfo<TItemData = any> = import('devextreme/common/core/events').ItemInfo<TItemData>;
            export type NativeEventInfo<TComponent, TNativeEvent = Event> = import('devextreme/common/core/events').NativeEventInfo<TComponent, TNativeEvent>;
            export const off = (CoreEventsModule as any).off as typeof import('devextreme/common/core/events').off;
            export const on = (CoreEventsModule as any).on as typeof import('devextreme/common/core/events').on;
            export const one = (CoreEventsModule as any).one as typeof import('devextreme/common/core/events').one;
            export const trigger = (CoreEventsModule as any).trigger as typeof import('devextreme/common/core/events').trigger;
        }
        export namespace Localization {
            export type Format = import('devextreme/common/core/localization').Format;
            export const formatDate = (CoreLocalizationModule as any).formatDate as typeof import('devextreme/common/core/localization').formatDate;
            export const formatMessage = (CoreLocalizationModule as any).formatMessage as typeof import('devextreme/common/core/localization').formatMessage;
            export const formatNumber = (CoreLocalizationModule as any).formatNumber as typeof import('devextreme/common/core/localization').formatNumber;
            export const loadMessages = (CoreLocalizationModule as any).loadMessages as typeof import('devextreme/common/core/localization').loadMessages;
            export const locale = (CoreLocalizationModule as any).locale as typeof import('devextreme/common/core/localization').locale;
            export const parseDate = (CoreLocalizationModule as any).parseDate as typeof import('devextreme/common/core/localization').parseDate;
            export const parseNumber = (CoreLocalizationModule as any).parseNumber as typeof import('devextreme/common/core/localization').parseNumber;
        }
    }
    export namespace Data {
        export const applyChanges = (DataModule as any).applyChanges as typeof import('devextreme/common/data').applyChanges;
        export const ArrayStore = (DataModule as any).ArrayStore as typeof import('devextreme/common/data').ArrayStore;
        export type ArrayStore<TItem = any, TKey = any> = import('devextreme/common/data').ArrayStore<TItem, TKey>;
        export type ArrayStoreOptions<TItem = any, TKey = any> = import('devextreme/common/data').ArrayStoreOptions<TItem, TKey>;
        export const base64_encode = (DataModule as any).base64_encode as typeof import('devextreme/common/data').base64_encode;
        export const compileGetter = (DataModule as any).compileGetter as typeof import('devextreme/common/data').compileGetter;
        export const compileSetter = (DataModule as any).compileSetter as typeof import('devextreme/common/data').compileSetter;
        export const CustomStore = (DataModule as any).CustomStore as typeof import('devextreme/common/data').CustomStore;
        export type CustomStore<TItem = any, TKey = any> = import('devextreme/common/data').CustomStore<TItem, TKey>;
        export type CustomStoreOptions<TItem = any, TKey = any> = import('devextreme/common/data').CustomStoreOptions<TItem, TKey>;
        export const DataSource = (DataModule as any).DataSource as typeof import('devextreme/common/data').DataSource;
        export type DataSource<TItem = any, TKey = any> = import('devextreme/common/data').DataSource<TItem, TKey>;
        export type DataSourceOptions<TStoreItem = any, TMappedItem = TStoreItem, TItem = TMappedItem, TKey = any> = import('devextreme/common/data').DataSourceOptions<TStoreItem, TMappedItem, TItem, TKey>;
        export const EdmLiteral = (DataModule as any).EdmLiteral as typeof import('devextreme/common/data').EdmLiteral;
        export type EdmLiteral = import('devextreme/common/data').EdmLiteral;
        export const EndpointSelector = (DataModule as any).EndpointSelector as typeof import('devextreme/common/data').EndpointSelector;
        export type EndpointSelector = import('devextreme/common/data').EndpointSelector;
        export const errorHandler = (DataModule as any).errorHandler as typeof import('devextreme/common/data').errorHandler;
        export type FilterDescriptor = import('devextreme/common/data').FilterDescriptor;
        export type GroupDescriptor<T> = import('devextreme/common/data').GroupDescriptor<T>;
        export type GroupingInterval = import('devextreme/common/data').GroupingInterval;
        export type GroupItem<TItem = any> = import('devextreme/common/data').GroupItem<TItem>;
        export const isGroupItemsArray = (DataModule as any).isGroupItemsArray as typeof import('devextreme/common/data').isGroupItemsArray;
        export const isItemsArray = (DataModule as any).isItemsArray as typeof import('devextreme/common/data').isItemsArray;
        export const isLoadResultObject = (DataModule as any).isLoadResultObject as typeof import('devextreme/common/data').isLoadResultObject;
        export const keyConverters = (DataModule as any).keyConverters as typeof import('devextreme/common/data').keyConverters;
        export type LangParams = import('devextreme/common/data').LangParams;
        export type LoadOptions<T = any> = import('devextreme/common/data').LoadOptions<T>;
        export type LoadResult<TItem = any> = import('devextreme/common/data').LoadResult<TItem>;
        export type LoadResultObject<TItem = any> = import('devextreme/common/data').LoadResultObject<TItem>;
        export const LocalStore = (DataModule as any).LocalStore as typeof import('devextreme/common/data').LocalStore;
        export type LocalStore<TItem = any, TKey = any> = import('devextreme/common/data').LocalStore<TItem, TKey>;
        export type LocalStoreOptions<TItem = any, TKey = any> = import('devextreme/common/data').LocalStoreOptions<TItem, TKey>;
        export const ODataContext = (DataModule as any).ODataContext as typeof import('devextreme/common/data').ODataContext;
        export type ODataContext = import('devextreme/common/data').ODataContext;
        export type ODataContextOptions = import('devextreme/common/data').ODataContextOptions;
        export const ODataStore = (DataModule as any).ODataStore as typeof import('devextreme/common/data').ODataStore;
        export type ODataStore<TItem = any, TKey = any> = import('devextreme/common/data').ODataStore<TItem, TKey>;
        export type ODataStoreOptions<TItem = any, TKey = any> = import('devextreme/common/data').ODataStoreOptions<TItem, TKey>;
        export const query = (DataModule as any).query as typeof import('devextreme/common/data').query;
        export type Query = import('devextreme/common/data').Query;
        export type ResolvedData<TItem = any> = import('devextreme/common/data').ResolvedData<TItem>;
        export type SearchOperation = import('devextreme/common/data').SearchOperation;
        export type SelectDescriptor<T> = import('devextreme/common/data').SelectDescriptor<T>;
        export const setErrorHandler = (DataModule as any).setErrorHandler as typeof import('devextreme/common/data').setErrorHandler;
        export type SortDescriptor<T> = import('devextreme/common/data').SortDescriptor<T>;
        export type Store<TItem = any, TKey = any> = import('devextreme/common/data').Store<TItem, TKey>;
        export type StoreOptions<TItem = any, TKey = any> = import('devextreme/common/data').StoreOptions<TItem, TKey>;
        export type SummaryDescriptor<T> = import('devextreme/common/data').SummaryDescriptor<T>;
    }
    export namespace Export {
        export namespace Excel {
            export type CellAddress = import('devextreme/common/export/excel').CellAddress;
            export type CellRange = import('devextreme/common/export/excel').CellRange;
            export type DataGridCell = import('devextreme/common/export/excel').DataGridCell;
            export type DataGridExportOptions = import('devextreme/common/export/excel').DataGridExportOptions;
            export const exportDataGrid = (ExportExcelModule as any).exportDataGrid as typeof import('devextreme/common/export/excel').exportDataGrid;
            export const exportPivotGrid = (ExportExcelModule as any).exportPivotGrid as typeof import('devextreme/common/export/excel').exportPivotGrid;
            export type PivotGridCell = import('devextreme/common/export/excel').PivotGridCell;
            export type PivotGridExportOptions = import('devextreme/common/export/excel').PivotGridExportOptions;
        }
        export namespace Pdf {
            export type Cell = import('devextreme/common/export/pdf').Cell;
            export type DataGridCell = import('devextreme/common/export/pdf').DataGridCell;
            export type DataGridExportOptions = import('devextreme/common/export/pdf').DataGridExportOptions;
            export const exportDataGrid = (ExportPdfModule as any).exportDataGrid as typeof import('devextreme/common/export/pdf').exportDataGrid;
            export const exportGantt = (ExportPdfModule as any).exportGantt as typeof import('devextreme/common/export/pdf').exportGantt;
            export type GanttExportFont = import('devextreme/common/export/pdf').GanttExportFont;
            export type GanttExportOptions = import('devextreme/common/export/pdf').GanttExportOptions;
        }
    }
  export function Grids(): void {}
}
