export const PAGER_CLASS = 'dx-pager';
export const LIGHT_MODE_CLASS = 'dx-light-mode';
export const PAGER_PAGES_CLASS = 'dx-pages';
export const PAGER_PAGE_INDEXES_CLASS = 'dx-page-indexes';
export const PAGER_PAGE_CLASS = 'dx-page';
export const PAGER_SELECTION_CLASS = 'dx-selection';
export const PAGER_PAGE_SIZE_CLASS = 'dx-page-size';
export const PAGER_PAGE_SIZES_CLASS = 'dx-page-sizes';
export const PAGER_SELECTED_PAGE_SIZE_CLASS = `${PAGER_PAGE_SIZE_CLASS} ${PAGER_SELECTION_CLASS}`;
