export type GridApplyFilterMode = 'auto' | 'onClick';
export type GridColumnButtonName = 'cancel' | 'delete' | 'edit' | 'save' | 'undelete';
export type GridColumnChooserMode = 'dragAndDrop' | 'select';
export type GridColumnDataType = 'string' | 'number' | 'date' | 'boolean' | 'object' | 'datetime';
export type GridColumnRenderingMode = 'standard' | 'virtual';
export type GridCommandColumnType = 'adaptive' | 'buttons' | 'detailExpand' | 'groupExpand' | 'selection' | 'drag';
export type GridDataChangeType = 'insert' | 'update' | 'remove';
export type GridEditMode = 'batch' | 'cell' | 'row' | 'form' | 'popup';
export type GridEditRefreshMode = 'full' | 'reshape' | 'repaint';
export type GridEnterKeyAction = 'startEdit' | 'moveFocus';
export type GridEnterKeyDirection = 'none' | 'column' | 'row';
export type GridFilterOperations = '=' | '<>' | '<' | '<=' | '>' | '>=' | 'contains' | 'endswith' | 'isblank' | 'isnotblank' | 'notcontains' | 'startswith' | 'between' | 'anyof' | 'noneof';
export type GridGroupingExpandMode = 'buttonClick' | 'rowClick';
export type GridNewRowPosition = 'first' | 'last' | 'pageBottom' | 'pageTop' | 'viewportBottom' | 'viewportTop';
export type GridPagerDisplayMode = 'adaptive' | 'compact' | 'full';
// eslint-disable-next-line @typescript-eslint/no-type-alias
export type GridPagerPageSize = 'all';
export type GridRowRenderingMode = 'standard' | 'virtual';
export type GridSelectionShowCheckBoxesMode = 'always' | 'none' | 'onClick' | 'onLongTap';
export type GridScrollingMode = 'infinite' | 'standard' | 'virtual';
export type GridSortingMode = 'multiple' | 'none' | 'single';
export type GridStartEditAction = 'click' | 'dblClick';
export type SummaryType = 'avg' | 'count' | 'custom' | 'max' | 'min' | 'sum';
