export {
  SpeechRecognitionConfig,
  CustomSpeechRecognizer,
  StartClickEvent,
  StopClickEvent,
  ResultEvent,
  ErrorEvent,
  EndEvent,
  ContentReadyEvent,
  DisposingEvent,
  InitializedEvent,
  OptionChangedEvent,
  dxSpeechToTextOptions,
  Properties,
} from './speech_to_text';
