export {
  SingleOrMultiple,
  Orientation,
  TabsIconPosition,
  TabsStyle,
  ContentReadyEvent,
  DisposingEvent,
  InitializedEvent,
  ItemClickEvent,
  ItemContextMenuEvent,
  ItemHoldEvent,
  ItemRenderedEvent,
  OptionChangedEvent,
  SelectionChangingEvent,
  SelectionChangedEvent,
  dxTabsOptions,
  Item,
  Properties,
} from './tabs';
