/*
 * The fluent-next component tier as a pure computation, shared by tests/fluent-next-naming.test.ts
 * (the guard) and tools/naming/publish.mjs (the emitter). Nothing here touches the file system:
 * callers hand in file contents, already stripped of comments where the parser expects it.
 *
 * Paths are POSIX and relative to scss/widgets (`fluent-next/button/_colors.scss`,
 * `base/button/_index.scss`), so the module needs no knowledge of where the package lives. The file
 * is loaded natively by Node (type stripping) and through ts-jest, which is why it imports nothing
 * but `node:path` and uses erasable syntax only.
 */

import { posix } from 'node:path';

export type SourceFile = {
  /** POSIX path relative to scss/widgets. */
  path: string;
  /** First folder under the theme, `''` for theme-root files. */
  folder: string;
  raw: string;
  stripped: string;
};

export type Use = { spec: string; star: boolean; alias: string | null };
export type NamespacedReference = { namespace: string; name: string };
export type Parsed = {
  path: string;
  folder: string;
  declarations: string[];
  /*
   * `references` intentionally contains both `$name` and the `name` half of `alias.$name`, because
   * the dead-variable check must see either form. Ownership checks must not: counting a namespaced
   * read as a bare one reports the same read twice the moment the variable's name becomes canonical.
   */
  references: string[];
  bareReferences: string[];
  namespacedReferences: NamespacedReference[];
  uses: Use[];
};

export type Registries = {
  components: Record<string, string>;
  declarationHome: Record<string, string>;
  exemptFolders: Record<string, string>;
  systemTier?: string[];
  migrated: string[];
  rootSelectors: Record<string, string[]>;
};

export type TierRecord = {
  component: string;
  value: string;
  reason: string | null;
  /** Declaring files, POSIX paths relative to scss/widgets. */
  sources: string[];
};

export type WiringKind = 'star' | 'feeder';
export type WiringEntry = { folder: string; variable: string; kind: WiringKind };

export type BaseIndex = {
  names: Set<string>;
  declarationsByPath: Map<string, string[]>;
};

export const THEME = 'fluent-next';
export const DECLARATION_FILE = /(^|\/)_(colors|sizes|variables)\.scss$/;
export const CSS_WIDE_KEYWORDS = new Set(['inherit', 'initial', 'unset', 'revert', 'revert-layer']);
export const PUBLIC_FILE = '_public.scss';
export const LINKS_FILE = '_public-links.scss';
export const COLLECTOR_FILE = '_public-tier.scss';
export const GENERATED_MARKER = '// GENERATED by tools/naming/publish.mjs';

const CONTROL_DIRECTIVES = /@(if|else|each|for|while)\b[^{]*$/;
const FEEDER_CALLS = /(?:icons?-mixin|icon-colored|data-uri|toggle-delete-icon)\s*\(((?:[^()]|\([^()]*\))*)\)/g;
const DECLARATION_LINE = /^\s*(\$[a-z0-9-]+)\s*:\s*([^;]*);(.*)$/;
const LINK_LINE = /^\s*(--dx-[a-z0-9-]+)\s*:\s*var\((--dx-[a-z0-9-]+)\);\s*$/;
const PROPERTY_LINE = /^\s*(--dx-[a-z0-9-]+)\s*:/;

// ---------------------------------------------------------------------------------------------
// parsing
// ---------------------------------------------------------------------------------------------

const findRanges = (content: string, opener: RegExp): [number, number][] => {
  const ranges: [number, number][] = [];
  let match = opener.exec(content);

  while (match !== null) {
    let depth = 1;
    let index = match.index + match[0].length;
    while (index < content.length && depth > 0) {
      if (content[index] === '(') depth += 1;
      if (content[index] === ')') depth -= 1;
      index += 1;
    }
    ranges.push([match.index, index]);
    match = opener.exec(content);
  }

  return ranges;
};

/**
 * Ranges of `@use … with ( … )` argument lists. Their left-hand sides are the *base module's*
 * parameter names, not declarations of this file, and must never be treated as either a declaration
 * or a foreign read.
 */
export const findWithRanges = (content: string): [number, number][] => findRanges(content, /\bwith\s*\(/g);

/**
 * Parameter lists of `@mixin` / `@function`. A parameter with a default (`$button-selected-bg: $x`)
 * looks exactly like a declaration and is not inside a `{}` block, so brace tracking alone counts it
 * as one — same trap as `with()` keys.
 */
export const findSignatureRanges = (content: string): [number, number][] => findRanges(
  content,
  /@(?:mixin|function)\s+[\w-]+\s*\(/g,
);

/**
 * Argument lists of `@include`. A named argument (`$checkbox-border-color-focused: $x`) binds the
 * base mixin's parameter by its own name: the key is base's spelling, exactly like a `with()` key,
 * and must not read as a declaration of this file.
 */
export const findIncludeRanges = (content: string): [number, number][] => findRanges(
  content,
  /@include\s+[\w.-]+\s*\(/g,
);

const inRanges = (position: number, ranges: [number, number][]): boolean => ranges
  .some(([from, to]) => position >= from && position < to);

/**
 * A declaration is module-level when every enclosing block is a control directive: Sass `@if`/`@each`
 * do not create scope, but a mixin, a function or a style rule do.
 */
export const parseScss = (path: string, folder: string, stripped: string): Parsed => {
  const content = stripped;
  const withRanges = [
    ...findWithRanges(content),
    ...findSignatureRanges(content),
    ...findIncludeRanges(content),
  ];
  const declarations: string[] = [];
  const references: string[] = [];
  const bareReferences: string[] = [];
  const namespacedReferences: NamespacedReference[] = [];
  const uses: Use[] = [];

  const blockStack: boolean[] = [];
  let index = 0;
  while (index < content.length) {
    const char = content[index];

    if (char === '{') {
      blockStack.push(CONTROL_DIRECTIVES.test(content.slice(Math.max(0, index - 200), index)));
      index += 1;
    } else if (char === '}') {
      blockStack.pop();
      index += 1;
    } else if (char === '$') {
      const name = /^\$[a-z0-9_-]+/i.exec(content.slice(index))?.[0];
      if (!name) { index += 1; continue; }
      const namespaced = index > 0 && content[index - 1] === '.';
      const after = content.slice(index + name.length);
      const isAssignment = /^\s*:/.test(after);
      const moduleLevel = blockStack.every((isControl) => isControl);

      if (isAssignment && !namespaced && moduleLevel && !inRanges(index, withRanges)) {
        declarations.push(name);
      } else if (!isAssignment && !namespaced) {
        references.push(name);
        bareReferences.push(name);
      } else if (!isAssignment && namespaced) {
        const namespace = /([a-zA-Z][a-zA-Z0-9_-]*)\.$/.exec(content.slice(0, index))?.[1];
        if (namespace) namespacedReferences.push({ namespace, name });
        references.push(name);
      }
      index += name.length;
    } else if (char === '@' && content.startsWith('@use', index)) {
      const statement = /^@use\s+["']([^"']+)["']/.exec(content.slice(index));
      if (statement) {
        // Only the module spec is consumed here. Scanning continues into the `with (…)` block: its
        // right-hand sides are ordinary references.
        const tail = content.slice(index + statement[0].length, index + statement[0].length + 200);
        const beforeArguments = tail.split(/;|\bwith\s*\(/)[0];
        uses.push({
          spec: statement[1],
          star: /\bas\s+\*/.test(beforeArguments),
          alias: /\bas\s+([a-zA-Z][a-zA-Z0-9_-]*)/.exec(beforeArguments)?.[1] ?? null,
        });
        index += statement[0].length;
      } else {
        index += 4;
      }
    } else {
      index += 1;
    }
  }

  return {
    path, folder, declarations, references, bareReferences, namespacedReferences, uses,
  };
};

export const parseSourceFile = (file: SourceFile): Parsed => parseScss(file.path, file.folder, file.stripped);

// ---------------------------------------------------------------------------------------------
// base wiring
// ---------------------------------------------------------------------------------------------

/**
 * `base/**` parameter names, keyed by file so a star import can be resolved to the exact module it
 * pulls in. The wide question ("does base declare this name anywhere") would wave through any
 * legacy name; the precise one is asked by `starredBaseParameters`.
 */
export const baseIndex = (baseFiles: SourceFile[]): BaseIndex => {
  const declarationsByPath = new Map<string, string[]>();
  const names = new Set<string>();
  baseFiles.forEach((file) => {
    const { declarations } = parseSourceFile(file);
    declarationsByPath.set(file.path, declarations);
    declarations.forEach((name) => names.add(name));
  });
  return { names, declarationsByPath };
};

/**
 * The base parameters a theme file wires by star-importing the very base module that declares them:
 * a top-level `$x: … !default` there SETS base's variable, so the name is base's spelling.
 */
export const starredBaseParameters = (parsed: Parsed, index: BaseIndex): Set<string> => {
  const names = new Set<string>();
  parsed.uses.forEach(({ spec, star }) => {
    if (!star || !spec.includes('base/')) return;
    const directory = posix.normalize(posix.join(posix.dirname(parsed.path), spec, '..'));
    const stem = spec.split('/').pop() as string;
    [posix.join(directory, `_${stem}.scss`), posix.join(directory, stem, '_index.scss')]
      .forEach((candidate) => (index.declarationsByPath.get(candidate) ?? [])
        .forEach((name) => names.add(name)));
  });
  return names;
};

/*
 * Base wiring is configuration, not ownership. Two shapes, both structural:
 *   - star: the file star-imports the very base module that declares the name, and the top-level
 *     `$x: … !default` SETS base's variable.
 *   - feeder: `$fluent-<baseName>` passed as a `with()` value for base's `-2` key.
 */
export const baseWiringKind = (variable: string, parsed: Parsed, index: BaseIndex): WiringKind | null => {
  if (starredBaseParameters(parsed, index).has(variable)) return 'star';
  if (variable.startsWith('$fluent-') && index.names.has(`$${variable.slice('$fluent-'.length)}`)) {
    return 'feeder';
  }
  return null;
};

export const baseWiringEntries = (
  parsedTheme: Parsed[],
  index: BaseIndex,
  exemptFolders: string[],
): WiringEntry[] => parsedTheme
  .flatMap((parsed) => parsed.declarations
    .map((variable) => ({ folder: parsed.folder, variable, kind: baseWiringKind(variable, parsed, index) }))
    .filter((entry): entry is WiringEntry => entry.kind !== null && !exemptFolders.includes(entry.folder)));

// ---------------------------------------------------------------------------------------------
// the tier: which variables are published, and why the rest are not
// ---------------------------------------------------------------------------------------------

export const systemTierOf = (registries: Registries): string[] => registries.systemTier ?? [];

export const tierFoldersOf = (component: string, registries: Registries): string[] => {
  if (systemTierOf(registries).includes(component)) return [component];
  const exempt = Object.keys(registries.exemptFolders);
  const folders = Object.entries(registries.components)
    .filter(([, owner]) => owner === component)
    .map(([folder]) => folder);
  const home = registries.declarationHome[component];
  if (home && !folders.includes(home)) folders.push(home);
  return folders.filter((folder) => !exempt.includes(folder));
};

/** Components that may publish: migrated plus the system tier, each once. */
export const publishingComponents = (registries: Registries): string[] => [
  ...new Set([...registries.migrated, ...systemTierOf(registries)]),
];

const inFolder = (file: SourceFile, folder: string): boolean => file.path.startsWith(`${THEME}/${folder}/`);

/** Which variables the tier MUST declare, and why the rest are excluded. */
export const tierRecords = (
  themeFiles: SourceFile[],
  registries: Registries,
  wiring: ReadonlySet<string>,
): Map<string, TierRecord> => {
  const records = new Map<string, TierRecord>();

  publishingComponents(registries).forEach((component) => {
    const declared = new Map<string, { value: string; marker: boolean; sources: string[] }>();
    const feeders = new Set<string>();
    tierFoldersOf(component, registries).forEach((folder) => {
      themeFiles.filter((file) => inFolder(file, folder)).forEach((file) => {
        if (DECLARATION_FILE.test(file.path)) {
          file.stripped.split('\n').forEach((line) => {
            const match = DECLARATION_LINE.exec(line);
            if (!match) return;
            const previous = declared.get(match[1]);
            const sources = previous?.sources ?? [];
            if (!sources.includes(file.path)) sources.push(file.path);
            declared.set(match[1], {
              value: match[2].trim().replace(/\s*!default$/, ''),
              marker: (previous?.marker ?? false) || /dx-data-uri-static/.test(match[3] + match[2]),
              sources,
            });
          });
        }
        // Feeder calls are read from the RAW file on purpose: a commented-out call still documents
        // that the variable bakes into an image somewhere.
        [...file.raw.matchAll(FEEDER_CALLS)]
          .forEach((call) => [...call[1].matchAll(/\$[a-z0-9-]+/g)]
            .forEach(([variable]) => feeders.add(variable)));
      });
    });
    declared.forEach(({ value, marker, sources }, variable) => {
      const reason = marker || feeders.has(variable) || /(^|[^\w-])data-uri\(/.test(value)
        ? 'data-uri'
        : wiring.has(variable) ? 'base-wiring'
          : CSS_WIDE_KEYWORDS.has(value) ? 'css-wide-keyword'
            : value.includes('!important') ? 'important'
              : value === 'null' ? 'null'
                : value === 'false' || value === 'true' ? 'sass-flag' : null;
      records.set(variable, {
        component, value, reason, sources,
      });
    });
  });

  // a reference to a data-uri-excluded name carries the same baked image, so the referrer is excluded too
  for (let changed = true; changed;) {
    changed = false;
    records.forEach((record) => {
      if (record.reason) return;
      if ([...record.value.matchAll(/\$[a-z0-9-]+/g)]
        .some(([token]) => records.get(token)?.reason === 'data-uri')) {
        record.reason = 'data-uri';
        changed = true;
      }
    });
  }
  return records;
};

// ---------------------------------------------------------------------------------------------
// the files
// ---------------------------------------------------------------------------------------------

export type Links = Map<string, string>; // --dx-a -> --dx-b

/** Codepoint order: what `sort()` without a comparator does, spelled out so nobody reaches for localeCompare. */
export const byCodepoint = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

export const propertyOf = (variable: string): string => `--dx-${variable.slice(1)}`;
export const variableOf = (property: string): string => `$${property.slice('--dx-'.length)}`;

/** A links file holds nothing but whole-value references; anything else is returned as a problem. */
export const parseLinksFile = (path: string, content: string): { links: Links; problems: string[] } => {
  const links: Links = new Map();
  const problems: string[] = [];
  content.split('\n').forEach((line, index) => {
    if (!PROPERTY_LINE.test(line)) return;
    const link = LINK_LINE.exec(line);
    if (!link) {
      problems.push(`${path}:${index + 1}: a links file may only hold \`--dx-a: var(--dx-b);\` lines`);
      return;
    }
    if (links.has(link[1])) problems.push(`${path}:${index + 1}: ${link[1]} is linked twice`);
    links.set(link[1], link[2]);
  });
  return { links, problems };
};

/** The `@use` spec that imports `sourcePath` from the directory of `publicPath`. */
export const useSpecFor = (publicPath: string, sourcePath: string): string => {
  const relative = posix.relative(posix.dirname(publicPath), sourcePath);
  const directory = posix.dirname(relative);
  const stem = posix.basename(relative, '.scss').replace(/^_/, '');
  return directory === '.' ? stem : posix.join(directory, stem);
};

export type Projection = { property: string; variable: string; sources: string[] };

export const renderPublicFile = (publicPath: string, projections: Projection[], hasLinks: boolean): string => {
  const specs = [...new Set(projections.flatMap(({ sources }) => sources
    .map((source) => useSpecFor(publicPath, source))))].sort(byCodepoint);
  const header = [
    GENERATED_MARKER,
    ...specs.map((spec) => `@use "${spec}" as *;`),
    ...(hasLinks ? [`@use "${LINKS_FILE.replace(/^_/, '').replace(/\.scss$/, '')}" as links;`] : []),
  ];
  const body = [...projections]
    .sort((a, b) => byCodepoint(a.property, b.property))
    .map(({ property, variable }) => `  ${property}: #{${variable}};`);
  if (hasLinks) body.push('  @include links.publish();');
  return `${header.join('\n')}\n\n@mixin publish {\n${body.join('\n')}\n}\n`;
};

export type CollectorEntry = { folder: string; selectors: string[] };

export const namespaceOf = (folder: string): string => `${folder}Public`;

/**
 * One rule per distinct selector list: the document root carries every system-tier folder and
 * stylelint forbids repeating a selector, so folders sharing a selector list share a rule.
 */
export const renderCollector = (entries: CollectorEntry[]): string => {
  const sorted = [...entries].sort((a, b) => byCodepoint(a.folder, b.folder));
  const uses = sorted.map(({ folder }) => `@use "${folder}/public" as ${namespaceOf(folder)};`);

  const groups = new Map<string, { selectors: string[]; folders: string[] }>();
  sorted.forEach(({ folder, selectors }) => {
    const key = selectors.join(',');
    const group = groups.get(key) ?? { selectors, folders: [] };
    group.folders.push(folder);
    groups.set(key, group);
  });
  const rules = [...groups.values()]
    .sort((a, b) => {
      const rootA = a.selectors.includes(':root') ? 0 : 1;
      const rootB = b.selectors.includes(':root') ? 0 : 1;
      return rootA - rootB || byCodepoint(a.folders[0], b.folders[0]);
    })
    .map(({ selectors, folders }) => `${selectors.join(',\n')} {\n${folders
      .map((folder) => `  @include ${namespaceOf(folder)}.publish();`).join('\n')}\n}`);

  return `${GENERATED_MARKER}\n${uses.join('\n')}\n\n${rules.join('\n\n')}\n`;
};

// ---------------------------------------------------------------------------------------------
// the plan: every generated file, or the reasons nothing can be written
// ---------------------------------------------------------------------------------------------

export type Publication = {
  /** Generated files by path, byte-exact. Empty when `problems` is not. */
  files: Map<string, string>;
  /** Paths of `_public.scss` files that did not exist before. */
  created: string[];
  problems: string[];
};

const publicPathOf = (folder: string): string => `${THEME}/${folder}/${PUBLIC_FILE}`;
const linksPathOf = (folder: string): string => `${THEME}/${folder}/${LINKS_FILE}`;
export const COLLECTOR_PATH = `${THEME}/${COLLECTOR_FILE}`;

export const planPublication = (
  themeFiles: SourceFile[],
  baseFiles: SourceFile[],
  registries: Registries,
  existing: ReadonlyMap<string, string>,
): Publication => {
  const problems: string[] = [];
  const exempt = Object.keys(registries.exemptFolders);
  const parsedTheme = themeFiles.map(parseSourceFile);
  const wiring = new Set(baseWiringEntries(parsedTheme, baseIndex(baseFiles), exempt)
    .map(({ variable }) => variable));
  const records = tierRecords(themeFiles, registries, wiring);

  // eligible variables per component, with the folder that declares them
  const perComponent = new Map<string, Projection[]>();
  records.forEach((record, variable) => {
    if (record.reason) return;
    const list = perComponent.get(record.component) ?? [];
    list.push({ property: propertyOf(variable), variable, sources: record.sources });
    perComponent.set(record.component, list);
  });

  // hand-written links per folder
  const linksByFolder = new Map<string, Links>();
  existing.forEach((content, path) => {
    if (!path.endsWith(`/${LINKS_FILE}`)) return;
    const parsed = parseLinksFile(path, content);
    problems.push(...parsed.problems);
    linksByFolder.set(path.split('/')[1], parsed.links);
  });

  // where each component's file lives: the folder that declares its eligible variables
  const homeOf = new Map<string, string>();
  const owners = new Map<string, string>(); // property -> component
  publishingComponents(registries).forEach((component) => {
    const folders = tierFoldersOf(component, registries);
    const declaring = [...new Set((perComponent.get(component) ?? [])
      .flatMap(({ sources }) => sources.map((source) => source.split('/')[1])))];
    const linking = folders.filter((folder) => (linksByFolder.get(folder)?.size ?? 0) > 0);
    const candidates = [...new Set([...declaring, ...linking])];
    if (candidates.length > 1) {
      problems.push(`${component}: variables are declared in several folders (${candidates.join(', ')}) — one home per component`);
      return;
    }
    if (candidates.length === 1) homeOf.set(component, candidates[0]);
    (perComponent.get(component) ?? []).forEach(({ property }) => {
      const owner = owners.get(property);
      if (owner && owner !== component) problems.push(`${property} is published by both ${owner} and ${component}`);
      owners.set(property, component);
    });
    folders.forEach((folder) => {
      linksByFolder.get(folder)?.forEach((_, property) => {
        const owner = owners.get(property);
        if (owner && owner !== component) problems.push(`${property} is published by both ${owner} and ${component}`);
        owners.set(property, component);
      });
    });
  });

  const publishesOnRoot = (component: string): boolean => (registries.rootSelectors[component] ?? []).includes(':root');

  // links: a target must be published where the referrer can see it, and a link may not shadow a value
  linksByFolder.forEach((links, folder) => {
    const component = systemTierOf(registries).includes(folder) ? folder : registries.components[folder];
    links.forEach((target, property) => {
      const eligible = (perComponent.get(component) ?? []).some((projection) => projection.property === property);
      if (eligible) {
        problems.push(`${linksPathOf(folder)}: ${property} is a link, but ${variableOf(property)} is declared and eligible — remove one of the two`);
      }
      if (target === property) {
        problems.push(`${linksPathOf(folder)}: ${property} links to itself`);
        return;
      }
      const owner = owners.get(target);
      if (!owner) {
        problems.push(`${linksPathOf(folder)}: ${property} links to ${target}, which nothing publishes`);
      } else if (owner !== component && !publishesOnRoot(owner)) {
        problems.push(`${linksPathOf(folder)}: ${property} links to ${target}, published on another component's root — publish the value instead`);
      }
    });
  });

  // stray files: a public file where the component has nothing to publish, or in a foreign folder
  existing.forEach((_, path) => {
    if (!path.endsWith(`/${PUBLIC_FILE}`)) return;
    const folder = path.split('/')[1];
    const component = systemTierOf(registries).includes(folder) ? folder : registries.components[folder];
    if (!component || !publishingComponents(registries).includes(component)) {
      problems.push(`${path}: ${folder} is not a publishing component — remove the file or register the component`);
      return;
    }
    const home = homeOf.get(component);
    if (home === undefined) {
      problems.push(`${path}: ${component} has nothing left to publish — remove the file by hand`);
    } else if (home !== folder) {
      problems.push(`${path}: ${component} publishes from ${home}/ — remove this copy`);
    }
  });

  homeOf.forEach((folder, component) => {
    if (!(registries.rootSelectors[component] ?? []).length) {
      problems.push(`${component} publishes from ${folder}/ but has no rootSelectors — add it to derive-registries.mjs OVERRIDES`);
    }
  });

  if (problems.length) return { files: new Map(), created: [], problems: [...new Set(problems)].sort(byCodepoint) };

  const files = new Map<string, string>();
  const created: string[] = [];
  const collector: CollectorEntry[] = [];
  homeOf.forEach((folder, component) => {
    const path = publicPathOf(folder);
    const hasLinks = (linksByFolder.get(folder)?.size ?? 0) > 0;
    files.set(path, renderPublicFile(path, perComponent.get(component) ?? [], hasLinks));
    if (!existing.has(path)) created.push(path);
    collector.push({ folder, selectors: registries.rootSelectors[component] });
  });
  files.set(COLLECTOR_PATH, renderCollector(collector));

  return { files, created: created.sort(byCodepoint), problems: [] };
};

/** Paths whose committed content differs from the plan — what `--check` reports. */
export const stalePaths = (plan: Publication, existing: ReadonlyMap<string, string>): string[] => [...plan.files]
  .filter(([path, content]) => existing.get(path) !== content)
  .map(([path]) => path)
  .sort(byCodepoint);
