name: Auto approve renovate bot PR

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: devextreme-shr2
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'renovate-bot' || github.actor == 'renovate[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
