name: "Pin Browsers"
description: "Install and setup Chrome and Firefox"

# List of browser versions
# Chrome:  https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
# Firefox: https://www.ubuntuupdates.org/package/ubuntu_mozilla_security/focal/main/base/firefox

inputs:
  chrome-version:
    description: "Chrome version to install"
    default: "latest"
  firefox-version:
    description: "Firefox version to install"
    default: "latest"

runs:
  using: composite
  steps:
    - name: "Setup latest Chrome"
      if: ${{ inputs.chrome-version == "latest" }}
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ inputs.chrome-version }}
    - name: "Setup Chrome with specific version"
      shell: bash
      if: ${{ inputs.chrome-version != "latest" }}
      env:
        CHROME_VERSION: ${{ inputs.chrome-version }}
      run: |
        if [ -n "$CHROME_VERSION" ]; then
          curl -L "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb" > /tmp/chrome.deb
          sudo dpkg -i /tmp/chrome.deb
          unlink /tmp/chrome.deb
          google-chrome-stable --version
        else
          echo "Skip Chrome upgrade"
        fi
    - name: "Setup Firefox"
      id: setup-firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ inputs.firefox-version }}
