/* eslint-disable spellcheck/spell-checker, @stylistic/max-len */
/**
 * HTML visualization template for Grid Core Architecture Documentation Generator.
 * Generates an interactive Cytoscape.js visualization.
 */

import { buildCytoscapeElements } from './graph-builder';
import type { ArchitectureData } from './types';

export function generateHtml(data: ArchitectureData): string {
  const cytoscapeElements = buildCytoscapeElements(data);
  const elementsJson = JSON.stringify(cytoscapeElements, null, 2);
  const featureAreas = [...new Set([
    ...data.modules.map((m) => m.featureArea),
    ...Object.values(data.standaloneControllers).map((c) => c.featureArea),
    ...Object.values(data.standaloneViews).map((v) => v.featureArea),
  ])].sort();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Grid Core Architecture</title>
<!-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. -->
<!-- Generated by: npx tsx __docs__/scripts/generate-architecture-doc.ts -->
<!-- Generated at: ${data.generatedAt} -->
<script src="https://unpkg.com/cytoscape@3.30.4/dist/cytoscape.min.js"></script>
<script src="https://unpkg.com/elkjs@0.9.3/lib/elk.bundled.js"></script>
<script src="https://unpkg.com/cytoscape-elk@2.2.0/dist/cytoscape-elk.js"></script>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; display: flex; height: 100vh; background: #1a1a1a; color: #E8E8E8; }

#sidebar {
  width: 260px; min-width: 260px; background: #2a2a2a; border-right: 1px solid #555;
  padding: 16px; overflow-y: auto; display: flex; flex-direction: column; gap: 16px;
}
#sidebar h2 { font-size: 14px; color: #aaa; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px; }
#sidebar label { display: flex; align-items: center; gap: 6px; font-size: 13px; cursor: pointer; padding: 2px 0; color: #E8E8E8; }
#sidebar input[type="checkbox"] { accent-color: #5B9BD5; }
#sidebar input[type="text"] {
  width: 100%; padding: 6px 10px; border: 1px solid #444; border-radius: 4px; font-size: 13px;
  background: #333; color: #E8E8E8; outline: none;
}
#sidebar input[type="text"]:focus-visible {
  border-color: #777; outline: none;
}
#sidebar button {
  padding: 6px 12px; border: 1px solid #555; border-radius: 4px; background: #333;
  cursor: pointer; font-size: 13px; transition: background 0.15s; color: #E8E8E8;
}
#sidebar button:hover { background: #444; }
.radio-group { display: flex; flex-direction: column; gap: 4px; }
.radio-group label { font-size: 12px; }

#main { flex: 1; display: flex; flex-direction: column; }
#cy { flex: 1; background: #212121; }

#info-panel {
  height: 140px; min-height: 80px; background: #2a2a2a; border-top: 1px solid #555;
  padding: 12px 16px; overflow-y: auto; font-size: 13px; line-height: 1.5; color: #E8E8E8;
}
#info-panel h3 { font-size: 14px; margin-bottom: 4px; color: #E8E8E8; }
#info-panel .label { color: #aaa; font-weight: 500; }
#info-panel .tag {
  display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 11px; margin: 1px 2px;
}
#info-panel .tag-ctrl { background: #243f62; color: #7CB9E8; }
#info-panel .tag-view { background: #3e2462; color: #C4A8FF; }
#info-panel .tag-ext { background: #3a2a1a; color: #C8884A; }

#legend {
  padding: 8px; font-size: 13px; border-top: 1px solid #555;
}
.legend-item { display: flex; align-items: center; gap: 6px; margin: 3px 0; color: #E8E8E8; }
.legend-swatch {
  width: 18px; height: 12px; border-radius: 2px; flex-shrink: 0;
}
.legend-line {
  width: 24px; height: 0; flex-shrink: 0;
}

.select-all-row { border-bottom: 1px solid #555; padding-bottom: 4px; margin-bottom: 2px; }
</style>
</head>
<body>
<div id="sidebar">
  <div>
    <h2>Search</h2>
    <input type="text" id="search" placeholder="Type to search..." />
  </div>
  <div>
    <h2>Edge Types</h2>
    <label><input type="checkbox" id="toggle-inheritance" checked> Inheritance</label>
    <label><input type="checkbox" id="toggle-extensions" checked> Extensions</label>
    <label><input type="checkbox" id="toggle-runtime" checked> Runtime Dependencies</label>
  </div>
  <div>
    <h2>Feature Areas</h2>
    <label class="select-all-row"><input type="checkbox" id="toggle-all-areas" checked> Select / Unselect All</label>
    ${featureAreas.map((area) => `<label><input type="checkbox" class="area-toggle" data-area="${area}" checked> ${area}</label>`).join('\n    ')}
  </div>
  <div>
    <h2>Orientation</h2>
    <div class="radio-group">
      <label><input type="radio" name="orientation" value="TB" checked> Top → Bottom</label>
      <label><input type="radio" name="orientation" value="LR"> Left → Right</label>
      <label><input type="radio" name="orientation" value="BT"> Bottom → Top</label>
      <label><input type="radio" name="orientation" value="RL"> Right → Left</label>
    </div>
    <h2 style="margin-top:10px;">Edge Routing</h2>
    <div class="radio-group">
      <label><input type="radio" name="edge-routing" value="taxi" checked> Orthogonal</label>
      <label><input type="radio" name="edge-routing" value="unbundled-bezier"> Bezier</label>
    </div>
  </div>
  <div>
    <button id="btn-fit">Fit View</button>
    <button id="btn-reset">Reset</button>
  </div>
  <div id="legend">
    <h2>Legend</h2>
    <div class="legend-item"><div class="legend-swatch" style="background:#3D6E9E;border:1px solid #2B5580;"></div> Controller</div>
    <div class="legend-item"><div class="legend-swatch" style="background:#6A4A9E;border:1px solid #4D3578;"></div> View</div>
    <div class="legend-item"><div class="legend-swatch" style="background:#333;border:2px dashed #C8884A;"></div> Extension-only Module</div>
    <div class="legend-item"><div class="legend-swatch" style="background:#3D6E9E;border:2px dashed #2B5580;"></div> Standalone (not in module)</div>
    <div class="legend-item"><div class="legend-swatch" style="background:#3a3a3a;border:1px solid #666;"></div> Module (compound)</div>
    <div class="legend-item"><div class="legend-line" style="border-top:2px solid #B0B0B0;"></div> Inheritance</div>
    <div class="legend-item"><div class="legend-line" style="border-top:2px dashed #C8884A;"></div> Extension</div>
    <div class="legend-item"><div class="legend-line" style="border-top:2px dotted #7A9DBF;"></div> Runtime Dependency</div>
  </div>
</div>
<div id="main">
  <div id="cy"></div>
  <div id="info-panel">
    <p style="color:#888;">Click a node or edge to see details.</p>
  </div>
</div>

<script>
const ELEMENTS = ${elementsJson};

// Helper: compute node width from label (replaces deprecated 'width': 'label')
function labelWidth(fontSize) {
  return function(ele) {
    const text = ele.data('label') || '';
    const charWidth = fontSize * 0.65;
    return Math.max(30, text.length * charWidth + 24);
  };
}

const cy = cytoscape({
  container: document.getElementById('cy'),
  elements: ELEMENTS,
  style: [
    // Compound nodes (modules)
    { selector: 'node.module',
      style: {
        'shape': 'round-rectangle',
        'background-color': '#3a3a3a',
        'background-opacity': 0.6,
        'border-width': 1,
        'border-color': '#666',
        'label': 'data(label)',
        'text-valign': 'top',
        'text-halign': 'center',
        'font-size': 11,
        'font-weight': 'bold',
        'color': '#E8E8E8',
        'padding': '12px',
        'text-margin-y': -4,
      }
    },
    // Extension-only modules
    { selector: 'node.module.ext-only',
      style: {
        'border-style': 'dashed',
        'border-width': 2,
        'border-color': '#C8884A',
        'background-color': '#3a3000',
        'min-width': 80,
        'min-height': 30,
      }
    },
    // Controller nodes
    { selector: 'node.controller',
      style: {
        'shape': 'hexagon',
        'background-color': '#3D6E9E',
        'border-width': 1,
        'border-color': '#2B5580',
        'label': 'data(label)',
        'text-valign': 'center',
        'text-halign': 'center',
        'font-size': 9,
        'color': '#E8E8E8',
        'width': labelWidth(9),
        'min-width': 30,
        'height': 30,
        'padding': '12px',
      }
    },
    // View nodes
    { selector: 'node.view',
      style: {
        'shape': 'round-rectangle',
        'background-color': '#6A4A9E',
        'border-width': 1,
        'border-color': '#4D3578',
        'label': 'data(label)',
        'text-valign': 'center',
        'text-halign': 'center',
        'font-size': 9,
        'color': '#E8E8E8',
        'width': labelWidth(9),
        'min-width': 30,
        'height': 26,
        'padding': '12px',
      }
    },
    // Standalone controller/view nodes (not inside a module) — dashed border
    { selector: 'node.standalone',
      style: {
        'border-style': 'dashed',
        'border-width': 2,
      }
    },
    // Inheritance edges (initial bezier; switched to taxi after layout)
    { selector: 'edge.inheritance',
      style: {
        'line-color': '#B0B0B0',
        'target-arrow-color': '#B0B0B0',
        'target-arrow-shape': 'triangle',
        'curve-style': 'bezier',
        'width': 2,
        'arrow-scale': 0.8,
      }
    },
    // Extension edges (initial bezier; switched to taxi after layout)
    { selector: 'edge.extension',
      style: {
        'line-color': '#C8884A',
        'target-arrow-color': '#C8884A',
        'target-arrow-shape': 'triangle',
        'line-style': 'dashed',
        'curve-style': 'bezier',
        'width': 1.5,
        'arrow-scale': 0.7,
        'opacity': 0.7,
      }
    },
    // Runtime dependency edges (initial bezier; switched to taxi after layout)
    { selector: 'edge.runtime',
      style: {
        'line-color': '#7A9DBF',
        'target-arrow-color': '#7A9DBF',
        'target-arrow-shape': 'triangle',
        'line-style': 'dotted',
        'curve-style': 'bezier',
        'width': 1,
        'arrow-scale': 0.6,
        'opacity': 0.7,
      }
    },
    // Highlighted state
    { selector: '.highlighted',
      style: { 'opacity': 1, 'z-index': 999 }
    },
    { selector: 'edge.highlighted',
      style: { 'opacity': 1, 'z-index': 999, 'width': 3 }
    },
    { selector: '.faded',
      style: { 'opacity': 0.08 }
    },
    { selector: 'node.search-match',
      style: { 'border-width': 3, 'border-color': '#FF6B6B' }
    },
    // Cross-compound edges must use bezier to avoid "invalid endpoints" warnings with taxi routing
    { selector: 'edge.cross-compound',
      style: {
        'curve-style': 'bezier',
      }
    },
  ],
  layout: { name: 'preset' },
});

// ── ELK Layout Helper ───────────────────────────
function getOrientation() {
  const checked = document.querySelector('input[name="orientation"]:checked');
  return checked ? checked.value : 'TB';
}

function toElkDirection(orient) {
  return { TB: 'DOWN', BT: 'UP', LR: 'RIGHT', RL: 'LEFT' }[orient] || 'DOWN';
}

function toTaxiDirection(orient) {
  return { TB: 'downward', BT: 'upward', LR: 'rightward', RL: 'leftward' }[orient] || 'downward';
}

function getEdgeRouting() {
  const checked = document.querySelector('input[name="edge-routing"]:checked');
  return checked ? checked.value : 'taxi';
}

function toElkEdgeRouting(curveStyle) {
  return curveStyle === 'taxi' ? 'ORTHOGONAL' : 'POLYLINE';
}

function updateEdgeStyles(orient) {
  const curveStyle = getEdgeRouting();

  if (curveStyle === 'taxi') {
    const dir = toTaxiDirection(orient);
    cy.edges().style({
      'curve-style': 'taxi',
      'taxi-direction': dir,
      'taxi-turn': '50%',
    });
    // Revert to bezier for edges with overlapping/adjacent endpoints
    cy.edges().forEach(function(edge) {
      const src = edge.source();
      const tgt = edge.target();
      if (tgt.data('parent') === src.id() || src.data('parent') === tgt.id()) {
        edge.style({ 'curve-style': 'bezier', 'taxi-direction': null, 'taxi-turn': null });
        return;
      }
      const sb = src.boundingBox();
      const tb = tgt.boundingBox();
      const overlaps = !(sb.x2 < tb.x1 || tb.x2 < sb.x1 || sb.y2 < tb.y1 || tb.y2 < sb.y1);
      if (overlaps) {
        edge.style({ 'curve-style': 'bezier', 'taxi-direction': null, 'taxi-turn': null });
      }
    });
  } else {
    cy.edges().style({
      'curve-style': curveStyle,
      'taxi-direction': null,
      'taxi-turn': null,
    });
  }
}

function buildLayoutOpts(layoutName, orient) {
  const elkEdgeRouting = toElkEdgeRouting(getEdgeRouting());
  return {
    name: 'elk',
    elk: {
      algorithm: 'layered',
      'elk.direction': toElkDirection(orient),
      'elk.layered.spacing.nodeNodeBetweenLayers': '100',
      'elk.layered.spacing.edgeNodeBetweenLayers': '50',
      'elk.spacing.nodeNode': '40',
      'elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX',
      'elk.layered.crossingMinimization.strategy': 'LAYER_SWEEP',
      'elk.hierarchyHandling': 'INCLUDE_CHILDREN',
      'elk.layered.mergeEdges': 'true',
      'elk.edgeRouting': elkEdgeRouting,
    },
    nodeDimensionsIncludeLabels: true,
    animate: true,
    animationDuration: 400,
  };
}

// Run initial layout, then apply taxi edge routing where safe
const initialLayoutOpts = buildLayoutOpts('elk-layered', 'TB');
initialLayoutOpts.stop = function() { updateEdgeStyles('TB'); };
cy.layout(initialLayoutOpts).run();

// ── Interactivity: hover / click-to-pin / edge highlight ──

function getVisibleEdges(eles) {
  const showInherit = document.getElementById('toggle-inheritance').checked;
  const showExt = document.getElementById('toggle-extensions').checked;
  const showRuntime = document.getElementById('toggle-runtime').checked;
  return eles.filter(function(ele) {
    if (!ele.isEdge()) return false;
    if (ele.hasClass('inheritance') && !showInherit) return false;
    if (ele.hasClass('extension') && !showExt) return false;
    if (ele.hasClass('runtime') && !showRuntime) return false;
    return ele.style('display') !== 'none';
  });
}

function connectedSet(seeds) {
  const edges = getVisibleEdges(seeds.connectedEdges());
  const neighbors = edges.connectedNodes();
  const parents = neighbors.parent();
  return seeds.union(edges).union(neighbors).union(parents);
}

function computeHighlightSet(target) {
  if (target.isEdge()) {
    const src = target.source();
    const tgt = target.target();
    return cy.collection().union(target).union(src).union(tgt)
      .union(src.parent()).union(tgt.parent());
  }
  const nodeType = target.data('nodeType');
  if (nodeType === 'module') {
    const children = target.children();
    const seeds = cy.collection().union(target).union(children);
    return connectedSet(seeds);
  }
  let leafSet = cy.collection().union(target);
  const par = target.parent();
  if (par.nonempty()) { leafSet = leafSet.union(par); }
  return connectedSet(leafSet);
}

function applyHighlight(highlightSet) {
  cy.elements().addClass('faded').removeClass('highlighted');
  highlightSet.removeClass('faded').addClass('highlighted');
}

function clearHighlight() {
  cy.elements().removeClass('faded').removeClass('highlighted');
}

// ── State ──────────────
let selectedTarget = null;

// ── Click to highlight ───────
cy.on('tap', 'node, edge', function(e) {
  const target = e.target;
  if (selectedTarget && selectedTarget.id() === target.id()) {
    selectedTarget = null;
    clearHighlight();
    infoPanel.innerHTML = '<p style="color:#888;">Click a node or edge to see details.</p>';
    return;
  }
  selectedTarget = target;
  const set = computeHighlightSet(target);
  applyHighlight(set);
});

cy.on('tap', function(e) {
  if (e.target === cy && selectedTarget) {
    selectedTarget = null;
    clearHighlight();
    infoPanel.innerHTML = '<p style="color:#888;">Click a node or edge to see details.</p>';
  }
});

// ── Info Panel ─────
const infoPanel = document.getElementById('info-panel');
cy.on('tap', 'node', function(e) {
  const d = e.target.data();
  let html = '<h3>' + (d.label || d.id) + '</h3>';
  if (d.nodeType === 'module') {
    html += '<p><span class="label">Source:</span> ' + (d.sourceFile || '') + '</p>';
    html += '<p><span class="label">Area:</span> ' + (d.featureArea || '') + '</p>';
    if (d.definesControllers) html += '<p><span class="label">Controllers:</span> ' + d.definesControllers + '</p>';
    if (d.definesViews) html += '<p><span class="label">Views:</span> ' + d.definesViews + '</p>';
    if (d.extendsControllers) html += '<p><span class="label">Extends (ctrl):</span> ' + d.extendsControllers + '</p>';
    if (d.extendsViews) html += '<p><span class="label">Extends (view):</span> ' + d.extendsViews + '</p>';
  } else if (d.nodeType === 'controller' || d.nodeType === 'view') {
    html += '<p><span class="label">Type:</span> ' + d.nodeType + '</p>';
    html += '<p><span class="label">Class:</span> ' + (d.className || '') + '</p>';
    html += '<p><span class="label">Base:</span> ' + (d.baseClass || '') + '</p>';
    if (d.mixins) html += '<p><span class="label">Mixins:</span> ' + d.mixins + '</p>';
    html += '<p><span class="label">Source:</span> ' + (d.sourceFile || '') + '</p>';
  }
  infoPanel.innerHTML = html;
});
cy.on('tap', 'edge', function(e) {
  const d = e.target.data();
  infoPanel.innerHTML = '<h3>Edge: ' + d.edgeType + '</h3>'
    + '<p><span class="label">From:</span> ' + d.source + '</p>'
    + '<p><span class="label">To:</span> ' + d.target + '</p>'
    + (d.extenderName ? '<p><span class="label">Extender:</span> ' + d.extenderName + '</p>' : '');
});

// ── Search ──────────────────────────────────────
document.getElementById('search').addEventListener('input', function(e) {
  const q = e.target.value.toLowerCase();
  cy.nodes().removeClass('search-match');
  if (!q) return;
  const matches = cy.nodes().filter(n => (n.data('label') || '').toLowerCase().includes(q) || n.data('id').toLowerCase().includes(q));
  matches.addClass('search-match');
  if (matches.length === 1) {
    cy.animate({ center: { eles: matches }, zoom: 1.5 }, { duration: 300 });
  } else if (matches.length > 0) {
    cy.animate({ fit: { eles: matches, padding: 50 } }, { duration: 300 });
  }
});

// ── Edge Type Toggles ───────────────────────────
function applyEdgeFilters() {
  const showInherit = document.getElementById('toggle-inheritance').checked;
  const showExt = document.getElementById('toggle-extensions').checked;
  const showRuntime = document.getElementById('toggle-runtime').checked;
  cy.edges('.inheritance').style('display', showInherit ? 'element' : 'none');
  cy.edges('.extension').style('display', showExt ? 'element' : 'none');
  cy.edges('.runtime').style('display', showRuntime ? 'element' : 'none');
  if (selectedTarget) {
    const set = computeHighlightSet(selectedTarget);
    cy.elements().removeClass('highlighted').addClass('faded');
    set.removeClass('faded').addClass('highlighted');
  }
}
document.getElementById('toggle-inheritance').addEventListener('change', applyEdgeFilters);
document.getElementById('toggle-extensions').addEventListener('change', applyEdgeFilters);
document.getElementById('toggle-runtime').addEventListener('change', applyEdgeFilters);

// ── Feature Area Toggles ────────────────────────
document.getElementById('toggle-all-areas').addEventListener('change', function() {
  const checked = this.checked;
  document.querySelectorAll('.area-toggle').forEach(cb => {
    cb.checked = checked;
    cb.dispatchEvent(new Event('change'));
  });
});
document.querySelectorAll('.area-toggle').forEach(cb => {
  cb.addEventListener('change', function() {
    const area = this.dataset.area;
    const show = this.checked;
    cy.nodes('[featureArea="' + area + '"]').forEach(n => {
      n.style('display', show ? 'element' : 'none');
      n.children().style('display', show ? 'element' : 'none');
      n.connectedEdges().forEach(e => {
        if (!show) e.style('display', 'none');
        else e.style('display', 'element');
      });
      n.children().connectedEdges().forEach(e => {
        if (!show) e.style('display', 'none');
        else e.style('display', 'element');
      });
    });
    applyEdgeFilters();
    const allToggles = document.querySelectorAll('.area-toggle');
    const allChecked = Array.from(allToggles).every(t => t.checked);
    const noneChecked = Array.from(allToggles).every(t => !t.checked);
    const selectAll = document.getElementById('toggle-all-areas');
    selectAll.checked = allChecked;
    selectAll.indeterminate = !allChecked && !noneChecked;
  });
});

// ── Layout Selector ─────────────────────────────
function rerunLayout() {
  const orient = getOrientation();
  const opts = buildLayoutOpts('elk-layered', orient);
  opts.stop = function() { updateEdgeStyles(orient); };
  cy.layout(opts).run();
}
document.querySelectorAll('input[name="orientation"]').forEach(radio => {
  radio.addEventListener('change', rerunLayout);
});
document.querySelectorAll('input[name="edge-routing"]').forEach(radio => {
  radio.addEventListener('change', rerunLayout);
});

// ── Buttons ─────────────────────────────────────
document.getElementById('btn-fit').addEventListener('click', () => cy.fit(undefined, 40));
document.getElementById('btn-reset').addEventListener('click', () => {
  selectedTarget = null;
  cy.elements().removeClass('faded highlighted search-match');
  document.getElementById('search').value = '';
  document.getElementById('toggle-all-areas').checked = true;
  document.getElementById('toggle-all-areas').indeterminate = false;
  document.querySelectorAll('.area-toggle').forEach(cb => { cb.checked = true; });
  cy.elements().style('display', 'element');
  document.getElementById('toggle-inheritance').checked = true;
  document.getElementById('toggle-extensions').checked = true;
  document.getElementById('toggle-runtime').checked = true;
  applyEdgeFilters();
  document.querySelector('input[name="orientation"][value="TB"]').checked = true;
  document.querySelector('input[name="edge-routing"][value="taxi"]').checked = true;
  updateEdgeStyles('TB');
  const resetOpts = buildLayoutOpts('elk-layered', 'TB');
  resetOpts.stop = function() { updateEdgeStyles('TB'); };
  cy.layout(resetOpts).run();
});
</script>
</body>
</html>`;
}
