import { THEME } from '../utils/visual-tests/helpers/theme-utils';

export const skippedTests = {
  jQuery: {
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    DataGrid: [
      { demo: 'RealTimeUpdates', themes: [THEME.material] },
      { demo: 'MultiRowHeadersBands', themes: [THEME.material] },
      { demo: 'ColumnReordering', themes: [THEME.material] },
      { demo: 'Row', themes: [THEME.material] },
    ],
    TreeList: [
      { demo: 'FilterRow', themes: [THEME.material] },
      { demo: 'PopupEditing', themes: [THEME.material] },
    ],
    DateRangeBox: [
      { demo: 'Formatting', themes: [THEME.material] },
    ],
    PivotGrid: [
      { demo: 'SummaryDisplayModes', themes: [THEME.material] },
      { demo: 'RunningTotals', themes: [THEME.material] },
      { demo: 'DrillDown', themes: [THEME.material] },
    ],
    Gauges: [
      { demo: 'DifferentSubvalueIndicatorTypesLinearGauge', themes: [THEME.material] },
      { demo: 'Tooltip', themes: [THEME.material] },
      { demo: 'ScaleLabelFormatting', themes: [THEME.material] },
      { demo: 'Palette', themes: [THEME.material] },
      { demo: 'ScaleCustomTickInterval', themes: [THEME.material] },
      { demo: 'GaugeTooltip', themes: [THEME.material] },
      { demo: 'CircularGauge', themes: [THEME.material] },
      { demo: 'ScaleCustomTickValues', themes: [THEME.material] },
      { demo: 'ScaleCustomTickValues', themes: [THEME.material] },
      { demo: 'SubvalueIndicatorTextFormatting', themes: [THEME.material] },
      { demo: 'DifferentValueIndicatorTypesLinearGauge', themes: [THEME.material] },
      { demo: 'GaugeTitleCustomized', themes: [THEME.material] },
      { demo: 'LabelsCustomization', themes: [THEME.material] },
      { demo: 'DifferentValueIndicatorTypes', themes: [THEME.material] },
      { demo: 'CustomLayout', themes: [THEME.material] },
      { demo: 'LinearGauge', themes: [THEME.material] },
    ],
    Gantt: [
      { demo: 'HeaderFilter', themes: [THEME.material] },
      { demo: 'ContextMenu', themes: [THEME.material] },
      { demo: 'DataBinding', themes: [THEME.material] },
      { demo: 'FilterRow', themes: [THEME.material] },
    ],
    Charts: [
      { demo: 'Line', themes: [THEME.material] },
      { demo: 'SmallValueGroups', themes: [THEME.material] },
      { demo: 'SankeyChart', themes: [THEME.material] },
      { demo: 'DoughnutSelection', themes: [THEME.material] },
      { demo: 'AreaSelectionZooming', themes: [THEME.material] },
      { demo: 'WindRose', themes: [THEME.material] },
      { demo: 'RangeBar', themes: [THEME.material] },
      { demo: 'Pie', themes: [THEME.material] },
      { demo: 'CustomBarWidth', themes: [THEME.material] },
      { demo: 'Colorization', themes: [THEME.material] },
      { demo: 'Bubble', themes: [THEME.material] },
      { demo: 'ZoomingAndScrolling', themes: [THEME.material] },
      { demo: 'TooltipAPI', themes: [THEME.material] },
      { demo: 'SplineArea', themes: [THEME.material] },
      { demo: 'DrillDown', themes: [THEME.material] },
      { demo: 'DiscretePointsAggregation', themes: [THEME.material] },
      { demo: 'ContinuousData', themes: [THEME.material] },
      { demo: 'PointsAggregation', themes: [THEME.material] },
      { demo: 'HierarchicalDataStructure', themes: [THEME.material] },
      { demo: 'RangeArea', themes: [THEME.material] },
      { demo: 'PieWithMultipleSeries', themes: [THEME.material] },
      { demo: 'MultiplePointSelection', themes: [THEME.material] },
      { demo: 'LogarithmicAxis', themes: [THEME.material] },
      { demo: 'CenterLabelCustomization', themes: [THEME.material] },
      { demo: 'PolarChartAnnotations', themes: [THEME.material] },
      { demo: 'PointImage', themes: [THEME.material] },
      { demo: 'PieResolveLabelOverlap', themes: [THEME.material] },
      { demo: 'PolarChartZoomingAndScrollingAPI', themes: [THEME.material] },
      { demo: 'StandardBar', themes: [THEME.material] },
      { demo: 'MultipleAxes', themes: [THEME.material] },
      { demo: 'InvertedChart', themes: [THEME.material] },
      { demo: 'BarColorCustomization', themes: [THEME.material] },
      { demo: 'Doughnut', themes: [THEME.material] },
      { demo: 'SideBySideFullStackedBar', themes: [THEME.material] },
      { demo: 'Stock', themes: [THEME.material] },
      { demo: 'StackedBar', themes: [THEME.material] },
      { demo: 'MultipleSeriesSelection', themes: [THEME.material] },
      { demo: 'DiscreteAxisZoomingAndScrolling', themes: [THEME.material] },
      { demo: 'CustomAnnotations', themes: [THEME.material] },
      { demo: 'EqualSizePies', themes: [THEME.material] },
      { demo: 'FlatDataStructure', themes: [THEME.material] },
      { demo: 'SpiderWeb', themes: [THEME.material] },
      { demo: 'ScaleBreaks', themes: [THEME.material] },
      { demo: 'DiscreteData', themes: [THEME.material] },
      { demo: 'SideBySideStackedBar', themes: [THEME.material] },
      { demo: 'PointSelectionAPI', themes: [THEME.material] },
      { demo: 'PieAnnotations', themes: [THEME.material] },
      { demo: 'DynamicSeries', themes: [THEME.material] },
      { demo: 'Spline', themes: [THEME.material] },
      { demo: 'MultiplePanes', themes: [THEME.material] },
      { demo: 'FullStackedBar', themes: [THEME.material] },
      { demo: 'ExportAndPrintingAPI', themes: [THEME.material] },
      { demo: 'AutoCalculatedBarWidth', themes: [THEME.material] },
      { demo: 'PointsAggregationFinancialChart', themes: [THEME.material] },
      { demo: 'ParetoChart', themes: [THEME.material] },
      { demo: 'LogarithmicVsLinearAxes', themes: [THEME.material] },
      { demo: 'LegendMarkersCustomization', themes: [THEME.material] },
      { demo: 'ExportSeveralCharts', themes: [THEME.material] },
      { demo: 'ClientSideDataProcessing', themes: [THEME.material] },
      { demo: 'Crosshair', themes: [THEME.material] },
      { demo: 'Selection', themes: [THEME.material] },
      { demo: 'FunnelChart', themes: [THEME.material] },
      { demo: 'Overview', themes: [THEME.material] },
      { demo: 'Candlestick', themes: [THEME.material] },
      { demo: 'BarDrillDown', themes: [THEME.material] },
    ],
    RangeSelector: [
      { demo: 'EmbeddedChart', themes: [THEME.material] },
      { demo: 'NumericScaleLightweight', themes: [THEME.material] },
      { demo: 'Calculation', themes: [THEME.material] },
      { demo: 'DateTimeScale', themes: [THEME.material] },
      { demo: 'EmbeddedChartCustomized', themes: [THEME.material] },
    ],
    Diagram: [
      { demo: 'WebAPIService', themes: [THEME.material] },
      { demo: 'ImagesInShapes', themes: [THEME.material] },
    ],
  },
  Angular: {
    Common: ['PopupAndNotificationsOverview'],
    DataGrid: ['SignalRService', 'MultipleRecordSelectionModes', 'RemoteCRUDOperations'],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['TaskTemplate', 'Validation'],
    Stepper: ['StepTemplate'],
  },
  React: {
    DataGrid: ['Toolbar', 'SignalRService', 'MultipleRecordSelectionModes'],
    // NOTE: 'GroupByDate' demo has problems with rendering
    Scheduler: ['GroupByDate'],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['Validation'],
  },
  Vue: {
    Common: ['PopupAndNotificationsOverview'],
    Charts: ['PointsAggregation'],
    DataGrid: ['SignalRService', 'MultipleRecordSelectionModes'],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['Validation'],
  },
};
