export const skippedTests = {
  jQuery: {
    Autocomplete: ['Overview'],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    DataGrid: [
      'ExcelJSExportMultipleGrids',
      'PDFExportMultipleGrids',
      'OdataService',
      'Overview',
      'FocusedRow',
      'FilteringAPI',
      'DeferredSelection',
    ],
    Charts: [
      'ServerSideDataProcessing',
    ],
    TreeView: ['VirtualMode'],
    FilterBuilder: ['WithDataGrid'],
  },
  Angular: {
    Autocomplete: ['Overview'],
    Charts: ['ServerSideDataProcessing'],
    Common: ['PopupAndNotificationsOverview'],
    DataGrid: [
      'MultipleRecordSelectionModes',
      'RemoteCRUDOperations',
      'ExcelJSExportMultipleGrids',
      'PDFExportMultipleGrids',
      'DeferredSelection',
      'FocusedRow',
      'OdataService',
      'FilteringAPI',
      'Overview',
    ],
    FilterBuilder: ['WithDataGrid'],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['TaskTemplate', 'Validation'],
    TreeView: ['LoadDataOnDemand', 'VirtualMode'],
    Stepper: ['StepTemplate'],
  },
  React: {
    Autocomplete: ['Overview'],
    Charts: ['ServerSideDataProcessing'],
    DataGrid: [
      'Overview',
      'Toolbar',
      'MultipleRecordSelectionModes',
      'ExcelJSExportMultipleGrids',
      'PDFExportMultipleGrids',
      'DeferredSelection',
      'FilteringAPI',
      'OdataService',
      'FocusedRow',
    ],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['Validation'],
    TreeView: ['VirtualMode'],
    FilterBuilder: ['WithDataGrid'],
  },
  Vue: {
    Autocomplete: ['Overview'],
    Common: ['PopupAndNotificationsOverview'],
    Charts: ['PointsAggregation', 'ServerSideDataProcessing'],
    DataGrid: [
      'MultipleRecordSelectionModes',
      'ExcelJSExportMultipleGrids',
      'PDFExportMultipleGrids',
      'OdataService',
      'Overview',
      'FocusedRow',
      'FilteringAPI',
      'DeferredSelection',
    ],
    Map: ['ProvidersAndTypes', 'Markers', 'Routes'],
    Gantt: ['Validation'],
    Scheduler: ['Toolbar'],
    TreeView: ['VirtualMode'],
    FilterBuilder: ['WithDataGrid'],
  },
};
