packages:
  - '.'

minimumReleaseAgeExclude:
  - '@devexpress/sbom-toolkit'

overrides:
  tar@<7.5.19: ^7.5.19
  brace-expansion@<5.0.8: ^5.0.8
  body-parser@>=2.0.0 <2.3.0: ^2.3.0
  fast-uri@>=3.0.0 <3.1.5: ^3.1.5
  undici@>=7.23.0 <7.29.0: ^7.29.0
  brace-expansion@>=3.0.0 <5.0.9: ^5.0.9
