export const products = [
  {
    Product_ID: 1,
    Product_Name: 'HD Video Player',
    Product_Sale_Price: 220.0,
    Product_Retail_Price: 330.0,
    Product_Consumer_Rating: 4,
    Product_Category: 'Video Players',
  },
  {
    Product_ID: 2,
    Product_Name: 'SuperHD Video Player',
    Product_Sale_Price: 275.0,
    Product_Retail_Price: 400.0,
    Product_Consumer_Rating: 4,
    Product_Category: 'Video Players',
  },
  {
    Product_ID: 3,
    Product_Name: 'SuperPlasma 50',
    Product_Sale_Price: 1800.0,
    Product_Retail_Price: 2400.0,
    Product_Consumer_Rating: 4.5,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 4,
    Product_Name: 'SuperLED 50',
    Product_Sale_Price: 1100.0,
    Product_Retail_Price: 1600.0,
    Product_Consumer_Rating: 5,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 5,
    Product_Name: 'SuperLED 42',
    Product_Sale_Price: 1050.0,
    Product_Retail_Price: 1450.0,
    Product_Consumer_Rating: 5,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 6,
    Product_Name: 'SuperLCD 55',
    Product_Sale_Price: 1045.0,
    Product_Retail_Price: 1350.0,
    Product_Consumer_Rating: 4.5,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 7,
    Product_Name: 'SuperLCD 42',
    Product_Sale_Price: 999.0,
    Product_Retail_Price: 1200.0,
    Product_Consumer_Rating: 4,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 8,
    Product_Name: 'SuperPlasma 65',
    Product_Sale_Price: 2900.0,
    Product_Retail_Price: 3500.0,
    Product_Consumer_Rating: 3,
    Product_Category: 'Televisions',
  },
  {
    Product_ID: 9,
    Product_Name: 'SuperLCD 70',
    Product_Sale_Price: 3200.0,
    Product_Retail_Price: 4000.0,
    Product_Consumer_Rating: 4,
    Product_Category: 'Televisions',
  },
];
