<template>
  <DxDiagram
    id="diagram"
    ref="diagram"
  >
    <DxCustomShape
      :category="'hardware'"
      :type="'internet'"
      :title="'Internet'"
      :background-image-url="'../../../../images/shapes/internet.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Internet'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'laptop'"
      :title="'Laptop'"
      :background-image-url="'../../../../images/shapes/laptop.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Laptop'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'mobile'"
      :title="'Mobile'"
      :background-image-url="'../../../../images/shapes/mobile.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Mobile'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'pc'"
      :title="'PC'"
      :background-image-url="'../../../../images/shapes/pc.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'PC'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'phone'"
      :title="'Phone'"
      :background-image-url="'../../../../images/shapes/phone.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Phone'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'printer'"
      :title="'Printer'"
      :background-image-url="'../../../../images/shapes/printer.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Printer'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'router'"
      :title="'Router'"
      :background-image-url="'../../../../images/shapes/router.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Router'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    />
    <DxCustomShape
      :category="'hardware'"
      :type="'scaner'"
      :title="'Scaner'"
      :background-image-url="'../../../../images/shapes/scaner.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Scaner'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'server'"
      :title="'Server'"
      :background-image-url="'../../../../images/shapes/server.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Server'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'switch'"
      :title="'Switch'"
      :background-image-url="'../../../../images/shapes/switch.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Switch'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxCustomShape
      :category="'hardware'"
      :type="'wifi'"
      :title="'Wi Fi Router'"
      :background-image-url="'../../../../images/shapes/wifi.svg'"
      :background-image-left="0.15"
      :background-image-top="0"
      :background-image-width="0.7"
      :background-image-height="0.7"
      :default-width="0.75"
      :default-height="0.75"
      :default-text="'Wi Fi'"
      :allow-edit-text="true"
      :text-left="0"
      :text-top="0.7"
      :text-width="1"
      :text-height="0.3"
    >
      <DxConnectionPoint
        :x="0.5"
        :y="0"
      />
      <DxConnectionPoint
        :x="0.9"
        :y="0.5"
      />
      <DxConnectionPoint
        :x="0.5"
        :y="1"
      />
      <DxConnectionPoint
        :x="0.1"
        :y="0.5"
      />
    </DxCustomShape>
    <DxToolbox :visible="true">
      <DxGroup
        :category="'hardware'"
        :title="'Hardware'"
      />
    </DxToolbox>
  </DxDiagram>
</template>
<script>
import { DxDiagram, DxGroup, DxToolbox, DxCustomShape, DxConnectionPoint } from 'devextreme-vue/diagram';
import 'whatwg-fetch';

export default {
  components: {
    DxDiagram, DxGroup, DxToolbox, DxCustomShape, DxConnectionPoint
  },
  mounted() {
    var diagram = this.$refs['diagram'].instance;
    fetch('../../../../data/diagram-hardware.json')
      .then(function(response) {
        return response.json();
      })
      .then(function(json) {
        diagram.import(JSON.stringify(json));
      })
      .catch(function() {
        throw 'Data Loading Error';
      });
  }
};
</script>
<style scoped>
    #diagram {
        height: 900px;
    }
</style>
