const houses = [{
  'ID': 1,
  'Address': '652 Avonwick Gate,  Toronto, ON M3A25',
  'Beds': 4,
  'Baths': 4,
  'HouseSize': 7500,
  'LotSize': 0.8,
  'Price': 780000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, 3/4 bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Hardwood flooring in kitchen, Kitchen island, Solid surface countertops in kitchen, Entry foyer, Front living room, Ceiling fan in master bedroom, Master bedroom separate from other, Mirrored door closet in master bedroom, 2nd bedroom: 11x13, 3rd bedroom: 11x14, 4th Bedroom: 18x13, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Convection oven, Double built-in gas ovens, Gas cooktop, Gas stove, Marble/Stone floors',
  'YearBuilt': 2008,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 2,
  'Address': '82649 Topeka St,  Riverbank, CA 95360',
  'Beds': 5,
  'Baths': 3,
  'HouseSize': 12500,
  'LotSize': 1.2,
  'Price': 1750000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Pantry, Walk-in pantry, Entry foyer, Formal living room, Rear living room, Vaulted ceiling in living room, Balcony in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 13X20, 3rd bedroom: 13X17, 4th Bedroom: 13X18, 5th Bedroom: 14X16, Alarm system owned, Blinds, Built-in electric oven, Built-in microwave, Carpet, Ceiling fan(s), Gas cooktop, Intercom system, Marble/Stone floors, Water conditioner owned, Water filtering system, Window Coverings Throughout',
  'YearBuilt': 2009,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 3,
  'Address': '328 S Kerema Ave,  Milford, CT 06465',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 8356,
  'LotSize': 0.04,
  'Price': 350000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 2nd floor, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Wet bar in family room, Breakfast nook (eating area), Garden window in kitchen, Granite countertops in kitchen, Kitchen island, Marble/Stone flooring in kitchen, Pantry, Formal living room, Front living room, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 16x12, 3rd bedroom: 13x16, 4th Bedroom: 18x12, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Double built-in electric ovens, Gas cooktop, Marble/Stone floors',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 4,
  'Address': '5119 Beryl Dr,  San Antonio, TX 78212',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 7980,
  'LotSize': 0.7,
  'Price': 455000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Full bath downstairs, Living/Dining room combo, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Recessed lighting in kitchen, Tile flooring in kitchen, Walk-in pantry, Formal living room, Front living room, Ceiling fan in master bedroom, Master bedroom downstairs, Walk-in closet in master bedroom, 2nd bedroom: 15x13, 3rd bedroom: 12x12, 4th Bedroom: 14x12, Alarm system owned, Blinds, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Convection oven, Double built-in electric ovens, Electric cooktop, Intercom system, Tile floors',
  'YearBuilt': 2007,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 5,
  'Address': '61207 16th St N,  Moorhead, MN 56564',
  'Beds': 5,
  'Baths': 4,
  'HouseSize': 14250,
  'LotSize': 1.1,
  'Price': 1700000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Formal living room, Rear living room, Sunken living room, Vaulted ceiling in living room, Balcony in master bedroom, Ceiling fan in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Walk-in closet in master bedroom, 2nd bedroom: 16X17, 3rd bedroom: 14X16, 4th Bedroom: 13X13, 5th Bedroom: 12X12, Blinds, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Double built-in electric ovens, Gas cooktop, Marble/Stone floors, Pot shelves, Water conditioner owned, Water filtering system, Window Coverings Throughout',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 6,
  'Address': '8512 Tanglewood Cir,  Reform, AL 35487',
  'Beds': 3,
  'Baths': 2,
  'HouseSize': 5600,
  'LotSize': 0.2,
  'Price': 250000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Full bath downstairs, Formal dining room, Built-in bookcases in family room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Marble/Stone flooring in kitchen, Pantry, Formal living room, Front living room, Ceiling fan in master bedroom, Master bedroom downstairs, Master bedroom separate from other, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 11X15, 3rd bedroom: 11X14, Alarm system owned, Blinds, Built-in microwave, Carpet, Ceiling fan(s), Double built-in electric ovens, Drapes, Electric cooktop, Marble/Stone floors, Window Coverings Throughout, Wine refrigerator',
  'YearBuilt': 2011,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 7,
  'Address': '7121 Bailey St,  Worcester, MA 01605',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 6900,
  'LotSize': 2.1,
  'Price': 555000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Kitchen island, Recessed lighting in kitchen, Tile countertops in kitchen, Walk-in pantry, Entry foyer, Formal living room, Front living room, Dressing room in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Walk-in closet in master bedroom, 2nd bedroom: 14x16, 3rd bedroom: 12x13, 4th Bedroom: 13x14, Carpet, Double built-in electric ovens, Drywall, Gas cooktop, Manmade wood or laminate floors, Marble/Stone floors, Water conditioner loope',
  'YearBuilt': 2008,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 8,
  'Address': '620201 Plymouth Rd,  Detroit, MI 48224',
  'Beds': 4,
  'Baths': 4,
  'HouseSize': 7840,
  'LotSize': 0.33,
  'Price': 610000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Full bath downstairs, Formal dining room, 2+ family rooms, Separate family room, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Walk-in pantry, Entry foyer, Formal living room, Rear living room, Vaulted ceiling in living room, Ceiling fan in master bedroom, Master bedroom downstairs, Walk-in closet in master bedroom, 2nd bedroom: 12x15, 3rd bedroom: 12x15, 4th Bedroom: 12x15, Blinds, Built-in microwave, Carpet, Ceiling fan(s), Electric cooktop, Shutters, Skylight(s), Water conditioner owned, Water filtering system, Window coverings partial',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 9,
  'Address': '1198 Theresa Cir,  Whitinsville, MA 01582',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 4990,
  'LotSize': 0.8,
  'Price': 320000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 1st floor, 1/2 bath downstairs, Formal dining room, 2+ family rooms, Built-in bookcases in family room, Breakfast Bar/Counter, Granite countertops in kitchen, Kitchen island, Tile flooring in kitchen, Walk-in pantry, Entry foyer, Formal living room, Built-in bookcases in master bedroom, Built-in entertainment center in master bedroom, Ceiling fan in master bedroom, Dressing room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 13x12, 3rd bedroom: 12x12, 4th Bedroom: 13x12, Alarm system rented, Blinds, Built-in microwave, Carpet, Ceiling fan(s), Double built-in gas ovens, Tile floors, Window Coverings Throughout',
  'YearBuilt': 2011,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 10,
  'Address': '420234 Rogge St,  Detroit, MI 48234',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 6900,
  'LotSize': 3.9,
  'Price': 320000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Granite countertops in kitchen, Kitchen custom cabinets, Vaulted ceiling in living room, Master bedroom downstairs, Master bedroom separate from other, 2nd bedroom: 12x15, 3rd bedroom: 13x13, 4th Bedroom: 12x14, Alarm system owned, Carpet, Ceiling fan(s), Double built-in gas ovens, Marble/Stone floors, Shutters, Window Coverings Throughout',
  'YearBuilt': 2007,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 11,
  'Address': '6677 Kingsbridge Ln,  Ridgewood, NJ 07454',
  'Beds': 5,
  'Baths': 4,
  'HouseSize': 14750,
  'LotSize': 0.99,
  'Price': 1100000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Dining area, Formal dining room, 2+ family rooms, Breakfast Bar/Counter, Kitchen island, Entry foyer, Rear living room, 2 master bedrooms, Balcony in master bedroom, Ceiling fan in master bedroom, Master bedroom downstairs, Master bedroom separate from other, Great room, 2nd bedroom: 15X13, 3rd bedroom: 11X12, 4th Bedroom: 11X12, 5th Bedroom: 11X10, Atrium(s), Blinds, Built-in gas oven, Carpet, Ceiling fan(s), Intercom system, Marble/Stone floors, Pot shelves',
  'YearBuilt': 2009,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 12,
  'Address': '4815 Warbler Ln,  Rockport, TX 78388',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 9600,
  'LotSize': 1.34,
  'Price': 700000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, Separate family room, Breakfast nook (eating area), Garden window in kitchen, Granite countertops in kitchen, Hardwood flooring in kitchen, Pantry, Entry foyer, Formal living room, Vaulted ceiling in living room, Master bedroom downstairs, Master bedroom separate from other, Walk-in closet in master bedroom, 2nd bedroom: 16X13, 3rd bedroom: 15X14, 4th Bedroom: 17X13, Blinds, Built-in electric oven, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Double built-in electric ovens, Electric stove, Intercom system, Shutters, Water conditioner owned',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 13,
  'Address': '115636 Hodges Ln,  Moundville, AL 35474',
  'Beds': 3,
  'Baths': 3,
  'HouseSize': 7550,
  'LotSize': 1.6,
  'Price': 450000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, 1/2 bath downstairs, Formal dining room, Separate family room, Breakfast Bar/Counter, Tile flooring in kitchen, Walk-in pantry, Formal living room, Front living room, Sunken living room, Ceiling fan in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 13X14, 3rd bedroom: 12X13, Blinds, Built-in electric oven, Carpet, Ceiling fan(s), Drapes, Drywall, Gas cooktop, Tile floors',
  'YearBuilt': 2011,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 14,
  'Address': '6351 Forrest St,  Jersey City, NJ 07308',
  'Beds': 4,
  'Baths': 4,
  'HouseSize': 10255,
  'LotSize': 0.3,
  'Price': 320000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Tile flooring in kitchen, Rear living room, Master bedroom upstairs, Walk-in closet in master bedroom, 2nd bedroom: 14x14, 3rd bedroom: 11x13, 4th Bedroom: 15x11, Carpet, Double built-in electric ovens, Marble/Stone floors, Tile floors',
  'YearBuilt': 2008,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 15,
  'Address': '1268 Bright St,  Jersey City, NJ 07308',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 5770,
  'LotSize': 1.3,
  'Price': 310000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, Built-in bookcases in family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Garden window in kitchen, Granite countertops in kitchen, Kitchen island, Recessed lighting in kitchen, Tile flooring in kitchen, Entry foyer, Formal living room, Sunken living room, Vaulted ceiling in living room, Ceiling fan in master bedroom, Master bedroom downstairs, Master bedroom separate from other, Walk-in closet in master bedroom, 2nd bedroom: 14x14, 3rd bedroom: 14x14, 4th Bedroom: 14x14, Alarm system owned, Built-in electric oven, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Electric cooktop, Intercom system, Marble/Stone floors, Shutters, Tile floors, Water conditioner loope, Window Coverings Throughout',
  'YearBuilt': 2008,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 16,
  'Address': '32125 4th St NW #2,  Washington, DC 20001',
  'Beds': 5,
  'Baths': 6,
  'HouseSize': 14600,
  'LotSize': 2.3,
  'Price': 2800000,
  'Features': 'Washer/Dryer on 1st floor, Washer/Dryer on 2nd floor, Full bath downstairs, Breakfast room/Nook, Formal dining room, Downstairs family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Recessed lighting in kitchen, Tile flooring in kitchen, Walk-in pantry, Built-in bookcases in living room, Entry foyer, Formal living room, Vaulted ceiling in living room, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, Great room, 2nd bedroom: 20X18, 3rd bedroom: 15X14, 4th Bedroom: 22X19, 5th Bedroom: 14X16, Alarm system owned, Built-in microwave, Carpet, Intercom system, Marble/Stone floors, Shutters, Warming drawer, Water conditioner owned, Window Coverings Throughout, Wine refrigerator',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 2,
}, {
  'ID': 17,
  'Address': '7700 Elmwood Dr,  Cleveland, OK 74021',
  'Beds': 4,
  'Baths': 4,
  'HouseSize': 8530,
  'LotSize': 0.45,
  'Price': 470000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Breakfast room/Nook, Kitchen/Dining room combo, 2+ family rooms, Upstairs & Downstairs family rooms, Wet bar in family room, Breakfast Bar/Counter, Breakfast nook (eating area), Garden window in kitchen, Granite countertops in kitchen, Kitchen custom cabinets, Recessed lighting in kitchen, Tile flooring in kitchen, Walk-in pantry, Entry foyer, Formal living room, Balcony in master bedroom, Ceiling fan in master bedroom, Master bedroom downstairs, Master bedroom separate from other, Walk-in closet in master bedroom, Great room, 2nd bedroom: 14X14, 3rd bedroom: 15X15, 4th Bedroom: 16X14, Alarm system owned, Blinds, Pot shelves, Tile floors, Water conditioner owned, Water filtering system, Window Coverings Throughout, Wine refrigerator',
  'YearBuilt': 2009,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 18,
  'Address': '8308 Vassar Ave,  Swarthmore, PA 19088',
  'Beds': 5,
  'Baths': 5,
  'HouseSize': 14100,
  'LotSize': 1.9,
  'Price': 1900000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, Built-in bookcases in family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Marble/Stone flooring in kitchen, Recessed lighting in kitchen, Walk-in pantry, Built-in bookcases in living room, Built-in entertainment center, Formal living room, Vaulted ceiling in living room, 2 master bedrooms, Dressing room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 17X13, 3rd bedroom: 16X12, 4th Bedroom: 21X21, 5th Bedroom: 12X16, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Convection oven, Double built-in electric ovens, Gas stove',
  'YearBuilt': 2009,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 19,
  'Address': '8913 Lakeshore Dr,  Jacksons Gap, AL 36863',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 12320,
  'LotSize': 0.87,
  'Price': 900000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Formal dining room, 2+ family rooms, Downstairs family room, Separate family room, Upstairs family room, Breakfast nook (eating area), Kitchen custom cabinets, Kitchen island, Tile countertops in kitchen, Walk-in pantry, Formal living room, Front living room, Vaulted ceiling in living room, Master bedroom downstairs, Master bedroom separate from other, Walk-in closet in master bedroom, 2nd bedroom: 16X13, 3rd bedroom: 16X13, 4th Bedroom: 20X14, Blinds, Built-in electric oven, Built-in microwave, Carpet, Gas cooktop, Pot shelves, Tile floors',
  'YearBuilt': 2007,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 20,
  'Address': '13673 Pearl Dr #7,  Monroe, MI 48161',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 7300,
  'LotSize': 0.3,
  'Price': 399000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, Separate family room, Breakfast Bar/Counter, Granite countertops in kitchen, Kitchen custom cabinets, Pantry, Formal living room, Ceiling fan in master bedroom, Master bedroom separate from other, Walk-in closet in master bedroom, 2nd bedroom: 15x15, 3rd bedroom: 13x12, 4th Bedroom: 14x12, Alarm system wired, Built-in microwave, Carpet, Ceiling fan(s), Central vacuum, Double built-in electric ovens, Gas cooktop, Marble/Stone floors, Tile floors, Window coverings partial',
  'YearBuilt': 2010,
  'Type': 0,
  'Status': 0,
}, {
  'ID': 21,
  'Address': '15447 Via Viento,  Atascadero, CA 93420',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 11300,
  'LotSize': 1.06,
  'Price': 1100000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 2nd floor, 3/4 bath downstairs, Formal dining room, Downstairs family room, Breakfast nook (eating area), Granite countertops in kitchen, Hardwood flooring in kitchen, Kitchen island, Pantry, Formal living room, Front living room, Sunken living room, Vaulted ceiling in living room, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 15X11, 3rd bedroom: 12X17, 4th Bedroom: 14X18, Blinds, Built-in microwave, Carpet, Double built-in electric ovens, Drywall, Tile floors, Window Coverings Throughout',
  'YearBuilt': 2007,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 22,
  'Address': '114840 Interlake Ave N,  Seattle, WA 98131',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 7990,
  'LotSize': 2.2,
  'Price': 400000,
  'Features': 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Full bath downstairs, Formal dining room, Living/Dining room combo, Downstairs family room, Separate family room, Breakfast Bar/Counter, Garden window in kitchen, Kitchen custom cabinets, Tile countertops in kitchen, Tile flooring in kitchen, Walk-in pantry, Entry foyer, Formal living room, Front living room, Vaulted ceiling in living room, Ceiling fan in master bedroom, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 18X15, 3rd bedroom: 18X15, 4th Bedroom: 17X11, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Double built-in gas ovens, Gas cooktop, Intercom system, Shutters, Tile floors, Water conditioner owned, Water filtering system',
  'YearBuilt': 2007,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 23,
  'Address': '1552 College Ave,  Winnipeg, MB R2W10',
  'Beds': 4,
  'Baths': 2,
  'HouseSize': 5200,
  'LotSize': 3.66,
  'Price': 330000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, 2+ family rooms, Separate family room, Upstairs & Downstairs family rooms, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Recessed lighting in kitchen, Tile flooring in kitchen, Entry foyer, Formal living room, Front living room, Vaulted ceiling in living room, Master bedroom separate from other, Walk-in closet in master bedroom, 2nd bedroom: 14X13, 3rd bedroom: 13X13, 4th Bedroom: 14X12, Blinds, Carpet, Ceiling fan(s), Double built-in electric ovens, Gas stove, Pot shelves, Tile floors',
  'YearBuilt': 2008,
  'Type': 0,
  'Status': 1,
}, {
  'ID': 24,
  'Address': '3929 Freedman St,  Jacksonville, IL 62656',
  'Beds': 4,
  'Baths': 3,
  'HouseSize': 6120,
  'LotSize': 1.7,
  'Price': 200000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Washer/Dryer on 1st floor, Full bath downstairs, Dining area, Family/Dining room combo, 2+ family rooms, Downstairs family room, Breakfast Bar/Counter, Granite countertops in kitchen, Kitchen custom cabinets, Recessed lighting in kitchen, Walk-in pantry, Entry foyer, Formal living room, Front living room, Master bedroom upstairs, Walk-in closet in master bedroom, 2nd bedroom: 12x14, 3rd bedroom: 12x13, 4th Bedroom: 13x16, Blinds, Built-in microwave, Carpet, Double built-in gas ovens, Drywall, Gas cooktop, Tile floors, Water conditioner owned, Window Coverings Throughout',
  'YearBuilt': 2011,
  'Type': 0,
  'Status': 2,
}, {
  'ID': 25,
  'Address': '54732 Crystal Dr,  Beulah, MI 49617',
  'Beds': 3,
  'Baths': 2,
  'HouseSize': 8300,
  'LotSize': 0.5,
  'Price': 590000,
  'Features': 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Living/Dining room combo, Built-in bookcases in family room, Separate family room, Breakfast Bar/Counter, Garden window in kitchen, Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Tile flooring in kitchen, Formal living room, Front living room, Built-in bookcases in master bedroom, Ceiling fan in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Walk-in closet in master bedroom, 2nd bedroom: 12X12, 3rd bedroom: 12X12, Blinds, Built-in microwave, Ceiling fan(s), Double built-in gas ovens, Gas cooktop, Manmade wood or laminate floors, Shutters, Tile floors, Window coverings partial, Window Coverings Throughout',
  'YearBuilt': 2009,
  'Type': 0,
  'Status': 0,
}];
