name: 'Prepare enviroment'
runs:
  using: "composite"
  steps:
    - name: Setup utils
      run: |
        sudo apt-get install -y dbus-x11 httping x11vnc xvfb

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    # - name: Restore npm cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ./node_modules
    #     key: ${{ runner.os }}-node-modules-v4-${{ hashFiles('**/package.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-modules-v4

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      env:
        DEVEXTREME_TEST_CI: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      run: npm run build
