const employees = [
  {
    ID: 3,
    FullName: 'Arthur Miller',
    Position: 'CTO',
    Picture: 'images/employees/10.png',
    Department: 'Management',
    Phone: '+1 (310) 555-8583',
    Email: 'arthurm@dx-email.com',
  },
  {
    ID: 4,
    FullName: 'Robert Reagan',
    Position: 'CMO',
    Picture: 'images/employees/03.png',
    Department: 'Management',
    Phone: '+1 (818) 555-2387',
    Email: 'robertr@dx-email.com',
  },
  {
    ID: 5,
    FullName: 'Greta Sims',
    Position: 'HR Manager',
    Picture: 'images/employees/04.png',
    Department: 'Human Resources',
    Phone: '+1 (818) 555-6546',
    Email: 'gretas@dx-email.com',
  },
  {
    ID: 6,
    FullName: 'Brett Wade',
    Position: 'IT Manager',
    Picture: 'images/employees/05.png',
    Department: 'IT',
    Phone: '+1 (626) 555-0358',
    Email: 'brettw@dx-email.com',
  },
  {
    ID: 7,
    FullName: 'Sandra Johnson',
    Position: 'Controller',
    Picture: 'images/employees/06.png',
    Department: 'Human Resources',
    Phone: '+1 (562) 555-2082',
    Email: 'sandraj@dx-email.com',
  },
  {
    ID: 8,
    FullName: 'Ed Holmes',
    Position: 'Sales Manager',
    Picture: 'images/employees/11.png',
    Department: 'Sales',
    Phone: '+1 (310) 555-1288',
    Email: 'edwardh@dx-email.com',
  },
  {
    ID: 9,
    FullName: 'Barb Banks',
    Position: 'Support Manager',
    Picture: 'images/employees/20.png',
    Department: 'Support',
    Phone: '+1 (310) 555-3355',
    Email: 'barbarab@dx-email.com',
  },
  {
    ID: 10,
    FullName: 'Kevin Carter',
    Position: 'Shipping Manager',
    Picture: 'images/employees/07.png',
    Department: 'Shipping',
    Phone: '+1 (213) 555-2840',
    Email: 'kevinc@dx-email.com',
  },
  {
    ID: 11,
    FullName: 'Cindy Stanwick',
    Position: 'HR Assistant',
    Picture: 'images/employees/08.png',
    Department: 'Human Resources',
    Phone: '+1 (818) 555-6655',
    Email: 'cindys@dx-email.com',
  },
  {
    ID: 12,
    FullName: 'Sammy Hill',
    Position: 'Sales Assistant',
    Picture: 'images/employees/12.png',
    Department: 'Sales',
    Phone: '+1 (626) 555-7292',
    Email: 'sammyh@dx-email.com',
  },
  {
    ID: 13,
    FullName: 'Davey Jones',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/13.png',
    Department: 'Shipping',
    Phone: '+1 (626) 555-0281',
    Email: 'davidj@dx-email.com',
  },
  {
    ID: 14,
    FullName: 'Victor Norris',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/14.png',
    Department: 'Shipping',
    Phone: '+1 (213) 555-9278',
    Email: 'victorn@dx-email.com',
  },
  {
    ID: 15,
    FullName: 'Mary Stern',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/15.png',
    Department: 'Shipping',
    Phone: '+1 (818) 555-7857',
    Email: 'marys@dx-email.com',
  },
  {
    ID: 16,
    FullName: 'Robin Cosworth',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/16.png',
    Department: 'Shipping',
    Phone: '+1 (818) 555-0942',
    Email: 'robinc@dx-email.com',
  },
  {
    ID: 17,
    FullName: 'Kelly Rodriguez',
    Position: 'Support Assistant',
    Picture: 'images/employees/17.png',
    Department: 'Support',
    Phone: '+1 (818) 555-9248',
    Email: 'kellyr@dx-email.com',
  },
  {
    ID: 18,
    FullName: 'James Anderson',
    Position: 'Support Assistant',
    Picture: 'images/employees/18.png',
    Department: 'Support',
    Phone: '+1 (323) 555-4702',
    Email: 'jamesa@dx-email.com',
  },
  {
    ID: 19,
    FullName: 'Antony Remmen',
    Position: 'Support Assistant',
    Picture: 'images/employees/19.png',
    Department: 'Support',
    Phone: '+1 (310) 555-6625',
    Email: 'anthonyr@dx-email.com',
  },
  {
    ID: 20,
    FullName: 'Olivia Peyton',
    Position: 'Sales Assistant',
    Picture: 'images/employees/09.png',
    Department: 'Sales',
    Phone: '+1 (310) 555-2728',
    Email: 'oliviap@dx-email.com',
  },
  {
    ID: 21,
    FullName: 'Taylor Riley',
    Position: 'Network Admin',
    Picture: 'images/employees/21.png',
    Department: 'IT',
    Phone: '+1 (310) 555-7276',
    Email: 'taylorr@dx-email.com',
  },
  {
    ID: 22,
    FullName: 'Amelia Harper',
    Position: 'Network Admin',
    Picture: 'images/employees/22.png',
    Department: 'IT',
    Phone: '+1 (213) 555-4276',
    Email: 'ameliah@dx-email.com',
  },
  {
    ID: 23,
    FullName: 'Wally Hobbs',
    Position: 'Programmer',
    Picture: 'images/employees/23.png',
    Department: 'IT',
    Phone: '+1 (818) 555-8872',
    Email: 'wallyh@dx-email.com',
  },
  {
    ID: 24,
    FullName: 'Brad Jameson',
    Position: 'Programmer',
    Picture: 'images/employees/24.png',
    Department: 'IT',
    Phone: '+1 (818) 555-4646',
    Email: 'bradleyj@dx-email.com',
  },
  {
    ID: 25,
    FullName: 'Karen Goodson',
    Position: 'Programmer',
    Picture: 'images/employees/25.png',
    Department: 'IT',
    Phone: '+1 (626) 555-0908',
    Email: 'kareng@dx-email.com',
  },
  {
    ID: 26,
    FullName: 'Marcus Orbison',
    Position: 'Travel Coordinator',
    Picture: 'images/employees/26.png',
    Department: 'Human Resources',
    Phone: '+1 (213) 555-7098',
    Email: 'marcuso@dx-email.com',
  },
  {
    ID: 27,
    FullName: 'Sandy Bright',
    Position: 'Benefits Coordinator',
    Picture: 'images/employees/27.png',
    Department: 'Human Resources',
    Phone: '+1 (818) 555-0524',
    Email: 'sandrab@dx-email.com',
  },
  {
    ID: 28,
    FullName: 'Morgan Kennedy',
    Position: 'Graphic Designer',
    Picture: 'images/employees/28.png',
    Department: 'IT',
    Phone: '+1 (818) 555-8238',
    Email: 'morgank@dx-email.com',
  },
  {
    ID: 29,
    FullName: 'Violet Bailey',
    Position: 'Jr Graphic Designer',
    Picture: 'images/employees/29.png',
    Department: 'IT',
    Phone: '+1 (818) 555-2478',
    Email: 'violetb@dx-email.com',
  },
  {
    ID: 30,
    FullName: 'Ken Samuelson',
    Position: 'Ombudsman',
    Picture: 'images/employees/02.png',
    Department: 'Human Resources',
    Phone: '+1 (562) 555-9282',
    Email: 'kents@dx-email.com',
  },
  {
    ID: 31,
    FullName: 'Nat Maguiree',
    Position: 'Trainer',
    Picture: 'images/employees/31.png',
    Department: 'Support',
    Phone: '+1 (562) 555-8377',
    Email: 'nataliem@dx-email.com',
  },
  {
    ID: 32,
    FullName: 'Bart Arnaz',
    Position: 'Director of Engineering',
    Picture: 'images/employees/32.png',
    Department: 'Engineering',
    Phone: '+1 (714) 555-2000',
    Email: 'barta@dx-email.com',
  },
  {
    ID: 33,
    FullName: 'Leah Simpson',
    Position: 'Test Coordinator',
    Picture: 'images/employees/33.png',
    Department: 'Engineering',
    Phone: '+1 (562) 559-5830',
    Email: 'leahs@dx-email.com',
  },
  {
    ID: 34,
    FullName: 'Arnie Schwartz',
    Position: 'Engineer',
    Picture: 'images/employees/34.png',
    Department: 'Engineering',
    Phone: '+1 (714) 555-8882',
    Email: 'arnolds@dx-email.com',
  },
  {
    ID: 35,
    FullName: 'Samantha Piper',
    Position: 'Engineer',
    Picture: 'images/employees/35.png',
    Department: 'Engineering',
    Phone: '+1 (323) 555-4512',
    Email: 'samanthap@dx-email.com',
  },
  {
    ID: 36,
    FullName: 'Maggie Boxter',
    Position: 'Engineer',
    Picture: 'images/employees/36.png',
    Department: 'Engineering',
    Phone: '+1 (714) 555-7239',
    Email: 'margaretb@dx-email.com',
  },
  {
    ID: 37,
    FullName: 'Terry Bradley',
    Position: 'QA Engineer',
    Picture: 'images/employees/37.png',
    Department: 'Engineering',
    Phone: '+1 (805) 555-2788',
    Email: 'terryb@dx-email.com',
  },
  {
    ID: 38,
    FullName: 'Gabe Jones',
    Position: 'Retail Coordinator',
    Picture: 'images/employees/38.png',
    Department: 'Support',
    Phone: '+1 (310) 555-5395',
    Email: 'gabrielj@dx-email.com',
  },
  {
    ID: 39,
    FullName: 'Lucy Ball',
    Position: 'Sales Assistant',
    Picture: 'images/employees/39.png',
    Department: 'Sales',
    Phone: '+1 (310) 555-3357',
    Email: 'lucyb@dx-email.com',
  },
  {
    ID: 40,
    FullName: 'Jim Packard',
    Position: 'Retail Sales Manager',
    Picture: 'images/employees/40.png',
    Department: 'Sales',
    Phone: '+1 (661) 555-8224',
    Email: 'jamesp@dx-email.com',
  },
  {
    ID: 41,
    FullName: 'Hannah Brookly',
    Position: 'Online Sales Manager',
    Picture: 'images/employees/41.png',
    Department: 'Sales',
    Phone: '+1 (805) 555-3627',
    Email: 'hannahb@dx-email.com',
  },
  {
    ID: 42,
    FullName: 'Harv Mudd',
    Position: 'Retail Sales Manager',
    Picture: 'images/employees/42.png',
    Department: 'Sales',
    Phone: '+1 (831) 555-3895',
    Email: 'harveym@dx-email.com',
  },
  {
    ID: 43,
    FullName: 'Clark Morgan',
    Position: 'Retail Sales Manager',
    Picture: 'images/employees/43.png',
    Department: 'Sales',
    Phone: '+1 (925) 555-2525',
    Email: 'clarkm@dx-email.com',
  },
  {
    ID: 44,
    FullName: 'Todd Hoffman',
    Position: 'Retail Sales Manager',
    Picture: 'images/employees/44.png',
    Department: 'Sales',
    Phone: '+1 (925) 555-3579',
    Email: 'toddh@dx-email.com',
  },
  {
    ID: 45,
    FullName: 'Jackie Garmin',
    Position: 'Support Assistant',
    Picture: 'images/employees/45.png',
    Department: 'Support',
    Phone: '+1 (213) 555-1824',
    Email: 'jackg@dx-email.com',
  },
  {
    ID: 46,
    FullName: 'Lincoln Bartlett',
    Position: 'Sales Assistant',
    Picture: 'images/employees/46.png',
    Department: 'Sales',
    Phone: '+1 (213) 555-8272',
    Email: 'lincolnb@dx-email.com',
  },
  {
    ID: 47,
    FullName: 'Brad Farkus',
    Position: 'Engineer',
    Picture: 'images/employees/47.png',
    Department: 'Engineering',
    Phone: '+1 (213) 555-3626',
    Email: 'bradf@dx-email.com',
  },
  {
    ID: 48,
    FullName: 'Jenny Hobbs',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/48.png',
    Department: 'Shipping',
    Phone: '+1 (310) 555-2668',
    Email: 'jennyh@dx-email.com',
  },
  {
    ID: 49,
    FullName: 'Dallas Lou',
    Position: 'Shipping Assistant',
    Picture: 'images/employees/49.png',
    Department: 'Shipping',
    Phone: '+1 (213) 555-8357',
    Email: 'dallas@dx-email.com',
  },
  {
    ID: 50,
    FullName: 'Stu Pizaro',
    Position: 'Engineer',
    Picture: 'images/employees/50.png',
    Department: 'Engineering',
    Phone: '+1 (213) 555-2552',
    Email: 'stu@dx-email.com',
  },
];
