name: 'Demos Build'
runs:
  using: "composite"
  steps:
    - name: Build devExtreme npm package
      uses: ./.github/actions/build_npm_devextreme

    - name: Clone devextreme-demos repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme-demos ./devextreme-demos

    - name: Clone devextreme-demos repo
      run: |
        BASE_BRANCH=$(node -p -e "require('./package.json').version.slice(0, 4).replace('.', '_')")
        test -d ./devextreme-demos || git clone -b $BASE_BRANCH https://github.com/devexpress/devextreme-demos ./devextreme-demos

    - name: Pack devextreme package
      working-directory: ./artifacts/npm/devextreme
      run: npm pack

    - name: Install packages for devextreme-demos
      working-directory: ./devextreme-demos
      run: npm install --no-audit --no-fund

    - name: Install devextreme package
      working-directory: ./devextreme-demos
      run: npm install $(find ../artifacts/npm/devextreme/ -maxdepth 1 -name "devextreme-*.tgz")

    - name: Zip node_modules    
      run: 7z a -t7z -mx3 -mmt2 node_modules.7z ./devextreme-demos/node_modules

    - name: Copy build artifacts      
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-demos-sources
        path: node_modules.7z
        retention-days: 1
