name: Lint

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [23_1]

jobs:
  Lint:
    name: Lint Monorepo
    runs-on: devextreme-shr2
    timeout-minutes: 30

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/**/node_modules
          playgrounds/**/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('./package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules-

    - name: Run npm install
      run: npm install --no-audit --no-fund
    - name: Build
      run: npx nx build @devextreme/jquery
    - name: Lint
      run: npm run lint

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [Lint]
    if: false

    steps:
      - uses: actions/checkout@v3
      - uses: DevExpress/github-actions/send-teams-notification@main
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
          specific_branch: 22_2
