name: Angular wrapper tests

on: [push, pull_request]

jobs:
  cache_build:
    concurrency: build-npm-devextreme-${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
    - name: Build devExtreme npm package
      uses: ./.github/actions/build_npm_devextreme

  test:
    needs: cache_build
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Build devExtreme npm package
      uses: ./.github/actions/build_npm_devextreme

    - name: Clone devextreme-angular repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme-angular ./devextreme-angular-repo

    - name: Clone devextreme-angular repo
      run: |
        test -d ./devextreme-angular-repo || git clone -b master https://github.com/devexpress/devextreme-angular ./devextreme-angular-repo

    - name: Install devextreme package
      run: |
        cd ./devextreme-angular-repo/packages/devextreme-angular
        npm install --save-dev ../../../artifacts/npm/devextreme

    - name: Run npm install for devextreme-angular repo
      run: |
        cd ./devextreme-angular-repo
        npm install --no-audit --no-fund

    - name: Update angular metadata
      run: |
        npm run internal-tool -- update-meta --output-path ./devextreme-angular-repo/packages/devextreme-angular/metadata/NGMetaData.json --version 21_2 --js-scripts ./js

    - name: Build with Angular 7
      run: |
        cd ./devextreme-angular-repo
        npm run build

    - name: Run tests with Angular 7
      run: |
        cd ./devextreme-angular-repo
        npx lerna run --scope devextreme-angular gulp -- run.tests
