name: Build and pack DevExtreme npm packages

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [26_1]
  workflow_dispatch:
    inputs:
      SBOM:
        description: 'Build SBOM'
        required: false
        default: false
        type: boolean

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ github.ref_name == github.event.repository.default_branch && secrets.NX_CLOUD_ACCESS_TOKEN || '' }}
  NX_SKIP_NX_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'skip-cache') && 'true' || 'false' }}

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
      - name: Get sources
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache

      - name: Install dependencies
        run:  pnpm install --frozen-lockfile

      - name: Build npm packages
        run: pnpm run all:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: devextreme-npm-packages
          path: |
            artifacts/npm/*.tgz
          retention-days: 1

      - name: Build SBOMs
        if: ${{ github.event_name == 'push' || github.event.inputs.SBOM == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm set //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN";
          pnpm nx build sbom;

      - name: Upload SBOM artifacts
        if: ${{ github.event_name == 'push' || github.event.inputs.SBOM == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: |
            packages/sbom/dist/**/*
          retention-days: 1

  custom_bundles:
    runs-on: devextreme-shr2
    needs: build

    steps:
      - name: Get sources
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Download npm packages
        uses: actions/download-artifact@v8
        with:
          name: devextreme-npm-packages
          path: npm

      - name: Move devextreme package
        run: mv ./npm/devextreme-2*.tgz ./e2e/devextreme-bundler/devextreme.tgz

      - name: Setup deps
        working-directory: ./e2e/devextreme-bundler
        run: |
          pnpm install --filter devextreme-bundler-test --frozen-lockfile
          pnpm add --filter devextreme-bundler-test ./devextreme.tgz

      - name: Build bundle
        working-directory: ./e2e/devextreme-bundler
        run: |
          pnpm exec devextreme-bundler-init custom-bundle
          pnpm exec devextreme-bundler custom-bundle
