name: Build and pack DevExtreme npm packages

on:
  pull_request:
  push:
    branches: [24_1]

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build npm packages
        run: npm run all:build

      - name: Copy build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: devextreme-npm-packages
          path: |
            artifacts/npm/*.tgz
          retention-days: 1
