name: Bindlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      env:
        DEVEXTREME_TEST_CI: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      run: npm run build

    - name: Build test bundle by webpack
      run: npx webpack --config ./testing/test_bundlers/webpack.config.js

    - name: Build test bundle by rollup
      run: npx rollup --config ./testing/test_bundlers/rollup.config.js
