name: Bundlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build

    - name: Create DevExtreme package
      working-directory: ./testing/bundlers  
      run: npm pack ../../artifacts/npm/devextreme
    
    - name: Install packages in test directory
      working-directory: ./testing/bundlers  
      run: npm install

    - name: Test src files
      working-directory: ./testig/bundlers
      run: npm run test

    - name: Prepare src files
      working-directory: ./testig/bundlers
      run: npm run create:src

    - name: Create bundle with webpack (CJS import)
      working-directory: ./testing/bundlers
      run: npm run build:webpack-cjs

    - name: Create bundle with webpack
      working-directory: ./testing/bundlers
      run: npm run build:webpack-esm

    - name: Create bundle with rollup
      working-directory: ./testing/bundlers
      run: npm run build:rollup-esm

    - name: Create bundle with parcel
      working-directory: ./testing/bundlers
      run: npm run build:parcel-esm

    - name: Create bundle with browserify
      working-directory: ./testing/bundlers
      run: npm run build:browserify-cjs

    - name: Create bundle with vite
      working-directory: ./testing/bundlers
      run: npm run build:vite-esm
