name: Bundlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build
    
    - name:  change the current working directory   
      run: cd ./testing/test_bundlers    

    - name: Run npm insatall in test directory
      run: npm install

    - name: Build test bundle by rollup
      run: npm run build-rollup

    - name: Build test bundle by webpack
      run: npm run build-webpack
