name: Bundlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build
    
    - name: Run npm insatall in test directory
      working-directory: ./testing/test_bundlers  
      run: npm install

    - name: Install DevExtreme in test directory
      working-directory:
      run: npm install ../../artifacts/npm/devextreme/    

    - name: Build test cjs import bundle by webpack
      working-directory: ./testing/test_bundlers
      run: npm run build:webpack-cjs

    - name: Build test esm import bundle by webpack
      working-directory: ./testing/test_bundlers
      run: npm run build:webpack-esm

    - name: Build test bundle by rollup
      working-directory: ./testing/test_bundlers
      run: npm run build:rollup-esm
