name: Bundlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build

    - name: Install packages in test directory
      working-directory: ./testing/bundlers  
      run: npm install

    # - name: Pack and install DevExtreme package
    #   working-directory: ./testing/bundlers  
    #   run: npm install $(npm pack ../../artifacts/npm/devextreme)
    
    - name: Pack and install win
      working-directory: ./testing/bundlers  
      run: npm run install:win

    - name: Pack and install ubuntu
      working-directory: ./testing/bundlers  
      run: npm run install:ununtu

    - name: Generate entry files
      working-directory: ./testing/bundlers
      run: npm run generate:entry

    - name: Run test
      working-directory: ./testing/bundlers
      run: npm run build:all
