name: Bindlers tests

on: [push, pull_request]

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build
    
    - run: npm install -g npm-check-updates  
    - run: npx ncu -u  

    - run: npm install
      
    - name: Install globalize
      run: npm install --save-dev devextreme-cldr-data globalize

    - name: Build test bundle by rollup
      run: npx rollup --config ./testing/test_bundlers/rollup.config.js

    - name: Build test bundle by webpack
      run: npx webpack --config ./testing/test_bundlers/webpack.config.js
