name: Code generation trigger

# TODO: think about concurrency!
#concurrency:
#  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
#  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [23_1]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger code generation
        run: |
          gh workflow run update-generated-code.yml -R DevExpress/devextreme-vue
          sleep 5
          latestRunId=$(gh run list -w update-generated-code.yml -R DevExpress/devextreme-vue --json databaseId --jq .[0].databaseId)
          gh run watch -R org/repo $latestRunId
    env:
      GITHUB_TOKEN: ${{ secrets.DX_ROBOT_PAT }}
