name: Demos unit tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [26_1]
  workflow_dispatch:

env:
  RUN_TESTS: true

jobs:
  check-should-run:
    name: Check if tests should run
    runs-on: devextreme-shr2
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Check RUN_TESTS flag
        id: check
        run: echo "should-run=${{ env.RUN_TESTS }}" >> $GITHUB_OUTPUT

  test:
    name: Run unit tests
    needs: check-should-run
    if: needs.check-should-run.outputs.should-run == 'true'

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Get sources
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'

      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        working-directory: apps/demos
        run: pnpm exec nx test
