name: CI

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 8 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
        - { TARGET: lint }
        - { TARGET: ts }
        - { TARGET: test, CONSTEL: export }
        - { TARGET: test, CONSTEL: misc }
        - { TARGET: test, CONSTEL: misc, TZ: 'PST8PDT' }
        - { TARGET: test, CONSTEL: misc, TZ: 'Japan' }
        - { TARGET: test, CONSTEL: misc, TZ: 'Australia/ACT' }
        - { TARGET: test, CONSTEL: ui }
        - { TARGET: test, CONSTEL: ui.editors }
        - { TARGET: test, CONSTEL: ui.editors, TZ: 'PST8PDT' }
        - { TARGET: test, CONSTEL: ui.editors, TZ: 'Japan' }
        - { TARGET: test, CONSTEL: ui.editors, TZ: 'Australia/ACT' }
        - { TARGET: test, CONSTEL: ui.grid }
        - { TARGET: test, CONSTEL: ui.grid, TZ: 'PST8PDT' }
        - { TARGET: test, CONSTEL: ui.scheduler }
        - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'PST8PDT' }
        - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'Japan' }
        - { TARGET: test, CONSTEL: ui.scheduler, TZ: 'Australia/ACT' }
        - { TARGET: test, CONSTEL: viz }
        - { TARGET: test, PERF: true, JQUERY: true, NO_HEADLESS: true }
        - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui }
        - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.editors, NO_HEADLESS: true }
        - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.grid }
        - { TARGET: test, MOBILE_UA: ios9, CONSTEL: ui.scheduler }
        - { TARGET: test, MOBILE_UA: ios9, CONSTEL: viz }
        - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui }
        - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.editors, NO_HEADLESS: true }
        - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.grid }
        - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: ui.scheduler }
        - { TARGET: test, MOBILE_UA: android6, JQUERY: true, CONSTEL: viz }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: export }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: misc }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.editors }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.grid }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: ui.scheduler }
        - { TARGET: test, BROWSER: firefox, JQUERY: true, CONSTEL: viz }
        - { TARGET: test_testcafe, COMPONENT: dataGrid, QUARANTINE_MODE: true }
        - { TARGET: test_testcafe, COMPONENT: scheduler, QUARANTINE_MODE: true }
        - { TARGET: test_testcafe, COMPONENT: editors }
        - { TARGET: test_testcafe, COMPONENT: navigation }
        - { TARGET: test_themebuilder }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Docker CI
        run: >
          docker run -t
          -e NO_HEADLESS=${{matrix.NO_HEADLESS}}
          -e TARGET=${{matrix.TARGET}}
          -e CONSTEL=${{matrix.CONSTEL}}
          -e BROWSER=${{matrix.BROWSER}}
          -e COMPONENT=${{matrix.COMPONENT}}
          -e JQUERY=${{matrix.JQUERY}}
          -e MOBILE_UA=${{matrix.MOBILE_UA}}
          -e PERF=${{matrix.PERF}}
          -e TZ=${{matrix.TZ}}
          -e QUARANTINE_MODE=${{matrix.QUARANTINE_MODE}}
          -v $GITHUB_WORKSPACE:/devextreme
          docker.io/devexpress/devextreme-build:20_1
          ./docker-ci.sh
