name: Health Check

on:
  workflow_dispatch:
  push:
    branches:
      - 26_1

jobs:
  invoke:
    name: Invoke
    uses: DevExpress/github-actions/.github/workflows/repository-check.yml@repository-check
    with:
      config: |
        {
          ignoredAdvisories: [
            'GHSA-67hx-6x53-jw92', // babel-traverse
            'GHSA-4wf5-vphf-c2xc', // terser
            'GHSA-2gmp-34j9-fqjm', // replicator
            'GHSA-848j-6mx2-7j84', // elliptic
          ]
        }
