name: Lint

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [26_1]

env:
  NX_SKIP_NX_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'skip-cache') && 'true' || 'false' }}

jobs:
  TS:
    runs-on: devextreme-shr2
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      working-directory: ./packages/devextreme
      run: pnpm exec nx build

    - name: Lint TS
      working-directory: ./packages/devextreme
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        DEBUG: eslint:cli-engine
      run: pnpm exec nx lint-ts

    - name: Lint .d.ts
      working-directory: ./packages/devextreme
      env:
        DEBUG: eslint:cli-engine
      run: pnpm exec nx lint-dts

    - name: Lint Testcafe tests
      working-directory: ./e2e/testcafe-devextreme
      env:
        DEBUG: eslint:cli-engine
      run: pnpm exec nx lint

  JS:
    runs-on: devextreme-shr2
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      working-directory: ./packages/devextreme
      run: pnpm exec nx build

    - name: Lint JS
      working-directory: ./packages/devextreme
      env:
        DEBUG: eslint:cli-engine
      run: pnpm exec nx lint-js

  texts:
    runs-on: devextreme-shr2
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Check texts
      working-directory: ./packages/devextreme
      run: pnpm exec nx lint-texts

  component_exports:
    runs-on: devextreme-shr2
    timeout-minutes: 10
    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Check generated component reexports
      working-directory: ./packages/devextreme
      run: |
        pnpm run update-ts-reexports

        git add . -N

        if git diff --exit-code ; then
          echo "Generated component reexports are up-to-date"
        else
            echo "Generated component reexports are outdated. Execute 'pnpm run update-ts-reexports' and commit changes."
            exit 1
        fi

  wrappers:
    runs-on: devextreme-shr2
    timeout-minutes: 10

    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint wrappers
      run: pnpm exec nx run-many -t lint -p devextreme-angular devextreme-react devextreme-vue

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [TS, JS, texts, component_exports]
    if: github.event_name != 'pull_request' && contains(needs.*.result, 'failure')

    steps:
      - uses: actions/checkout@v6
      - uses: DevExpress/github-actions/send-teams-notification@v1
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
