name: Publishing to GitHub Packages (scheduler)

on:
  schedule:
    - cron: '00 18 * * *'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    strategy:
      matrix:
        branch: ['24_2', '25_1', '25_2', '26_1']

    name: Run Packages Publishing workflow
    uses: ./.github/workflows/packages_publishing.yml
    with:
      tag: daily
      branch: ${{ matrix.branch }}
    secrets: inherit
