name: Pack all DevExtreme npm packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages in devextreme repo
        run: npm install --no-audit --no-fund

      - name: Build npm packages
        run: npm run all:pack

      - name: Copy build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: devextreme-npm-packages
          path: |
            npm/*.tgz
          retention-days: 1
