name: Schedule daily publishing to GitHub Packages

on:
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        branch: ['23_2', '24_1']

    name: Run Packages Publishing workflow
    steps:
      - name: Get sources
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - name: Publish Packages (${{ matrix.branch }})
        run: |
          gh workflow run packages_publishing.yml -f tag=daily --ref ${{ matrix.branch }}          
