name: Paths length check

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [24_1]

env:
  MAX_LENGTH: 170
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_TOKEN }}
  NX_SKIP_NX_CACHE: ${{ (github.event_name != 'pull_request' || contains( github.event.pull_request.labels.*.name, 'skip-cache')) && 'true' || 'false' }}

jobs:
  checks:
    runs-on: devextreme-shr2
    timeout-minutes: 5
    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        separator: "\" \""

    - name: Check all changed files
      run: |
        RESULT=''
        for file in "${{ steps.changed-files.outputs.all_changed_files }}"; do
          if (( ${#file} > $MAX_LENGTH )); then RESULT+="$file\n"; fi;
        done
        if (( ${#RESULT} )); then printf "The following filenames are longer than $MAX_LENGTH characters:\n${RESULT}" && exit 1; fi;

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [checks]
    if: github.event_name != 'pull_request' && contains(needs.*.result, 'failure')

    steps:
      - uses: actions/checkout@v4
      - uses: DevExpress/github-actions/send-teams-notification@main
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
