name: Paths length check

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [23_2]

env:
  NX_SKIP_NX_CACHE: ${{ (github.event_name != 'pull_request' || contains( github.event.pull_request.labels.*.name, 'skip-cache')) && 'true' || 'false' }}

jobs:
  Checks:
    runs-on: devextreme-shr2
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v38

    - name: Check all changed files
      run: |
        MAX_LENGTH=150
        RESULT=''
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if (( ${#file} > MAX_LENGTH )); then RESULT+="$file\n"; fi;
        done
        if (( ${#RESULT} )); then printf "The following filenames are longer than ${MAX_LENGTH} characters:\n${RESULT}" && exit 1; fi;

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [Checks]
    if: always() && contains(needs.*.result, 'failure')

    steps:
      - uses: actions/checkout@v3
      - uses: DevExpress/github-actions/send-teams-notification@main
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
          specific_branch: 23_2
