name: Playgrounds tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [26_1]

env:
  NX_SKIP_NX_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'skip-cache') && 'true' || 'false' }}

jobs:
  build:
    name: build
    strategy:
      fail-fast: false

    runs-on: devextreme-shr2
    timeout-minutes: 15

    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      working-directory: ./packages/devextreme
      run: pnpm exec nx build

    - name: Zip artifacts
      working-directory: ./packages/devextreme
      run: |
        7z a -tzip -mx3 -mmt2 artifacts.zip artifacts ../devextreme-scss/scss/bundles

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: devextreme-artifacts
        path: ./packages/devextreme/artifacts.zip
        retention-days: 1

  test:
    name: ${{ matrix.ARGS.platform }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        ARGS: [
          { platform: "angular" },
          { platform: "react" },
          { platform: "vue" },
        ]
    runs-on: devextreme-shr2
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v6

    - name: Setup Chrome
      uses: ./.github/actions/setup-chrome
      with:
        chrome-version: '145.0.7632.67'

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: devextreme-artifacts
        path: ./packages/devextreme

    - name: Unpack artifacts
      working-directory: ./packages/devextreme
      run: 7z x artifacts.zip -aoa

    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v5
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-cache

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      working-directory: ./packages/devextreme-${{ matrix.ARGS.platform }}
      run: pnpm exec nx pack

    - name: Check sources compilation
      working-directory: ./apps/${{ matrix.ARGS.platform }}
      run: pnpm exec nx build

#    - name: Run test
#      if: ${{ matrix.ARGS.platform != 'angular' }}
#      working-directory: ./apps/${{ matrix.ARGS.platform }}
#      run: pnpm run test
