name: PR Filter Stubs

on:
  pull_request:
    paths:
      - 'apps/**/*.md'

jobs:

  changesSegregation:
    name: Changes Segregation Check
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MONOREPO_ALERTS_FGPAT }}
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: .md files filter
        id: mdFilesFilter
        uses: DevExpress/github-actions/pr-filter@v1
        with:
          paths: '**;!apps/**/*.md'
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show warning for .md files
        if: steps.mdFilesFilter.outputs.result == 'true'
        uses: actions/github-script@v9
        with:
          script: core.setFailed('Changes in apps/**/*.md shouldn\'t be mixed with changes in other files')

  # build_all.yml, demos_visual_tests.yml, packages_publishing.yml, playgrounds_tests.yml, qunit_tests.yml, testcafe_tests.yml
  build1:
    name: 'build'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  #default_workflow.yml
  default_workflow1:
    name: 'main'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  # lint.yml
  lint1:
    name: 'Renovation'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  lint2:
    name: 'TS'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  lint3:
    name: 'JS'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  lint4:
    name: 'CSS'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  # styles.yml
  styles1:
    name: 'Tests'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  # renovation.yml
  renovation1:
    name: 'jest-tests'
    needs: [ changesSegregation ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  # qunit_tests
  qunit_tests1:
    name: 'Constel export'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests2:
    name: 'Constel misc'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests3:
    name: 'Constel ui'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests4:
    name: 'Constel ui.scheduler-US/Pacific'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests5:
    name: 'Constel misc-no-csp'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests6:
    name: 'Constel ui.widgets-no-csp'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests7:
    name: 'Constel ui.editors'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests8:
    name: 'Constel ui.grid'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests9:
    name: 'Constel ui.scheduler'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests10:
    name: 'ui-shadow-dom'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests11:
    name: 'ui.widgets-shadow-dom'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests12:
    name: 'ui.editors-shadow-dom'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests13:
    name: 'ui.grid-shadow-dom'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  qunit_tests14:
    name: 'ui.scheduler-shadow-dom'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  # demos_visual_tests.yml
  demos_visual_tests1:
    name: 'jquery(1/3)-screenshots-material.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests2:
    name: 'jquery(2/3)-screenshots-material.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests3:
    name: 'jquery(3/3)-screenshots-material.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests4:
    name: 'jquery(1/3)-screenshots-fluent.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests5:
    name: 'jquery(2/3)-screenshots-fluent.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests6:
    name: 'jquery(3/3)-screenshots-fluent.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  demos_visual_tests7:
    name: 'jquery-accessibility-fluent.blue.light'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  # testcafe_tests.yml
  testcafe_tests1:
    name: 'accessibility - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests2:
    name: 'common - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests3:
    name: 'generic'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests4:
    name: 'material'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests5:
    name: 'material - compact'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests6:
    name: 'cardView - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests7:
    name: 'dataGrid (1/4) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests8:
    name: 'dataGrid (2/4) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests9:
    name: 'dataGrid (3/4) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests10:
    name: 'dataGrid (4/4) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_test11:
    name: 'editors - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests12:
    name: 'navigation - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests13:
    name: 'scheduler / common (1/3) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests14:
    name: 'scheduler / common (2/3) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests15:
    name: 'scheduler / common (3/3) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests16:
    name: 'scheduler / viewOffset (1/2) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests17:
    name: 'scheduler / viewOffset (2/2) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests18:
    name: 'scheduler / timezones (Europe/Berlin) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
  testcafe_tests19:
    name: 'scheduler / timezones (America/Los_Angeles) - fluent'
    needs: [ changesSegregation ]
    if: false
    runs-on: devextreme-shr2
    steps:
      - run: exit 1
