name: Publish Demos to gh-pages branch

on:
  workflow_dispatch:

jobs:
  build-devextreme:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 20

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: DevExtreme - Install packages
        run: pnpm install

      - name: DevExtreme - Build-all
        env:
          BUILD_TEST_INTERNAL_PACKAGE: true
        run: pnpm run all:build

      - name: Move packages
        run: |
          mv ./packages/devextreme/artifacts/pnpm/devextreme/*.tgz ./devextreme-installer.tgz
          mv ./packages/devextreme/artifacts/pnpm/devextreme-dist/*.tgz ./devextreme-dist-installer.tgz
          mv ./packages/devextreme-angular/pnpm/dist/*.tgz ./devextreme-angular-installer.tgz
          mv ./packages/devextreme-react/pnpm/*.tgz ./devextreme-react-installer.tgz
          mv ./packages/devextreme-vue/pnpm/*.tgz ./devextreme-vue-installer.tgz

      - name: Copy build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devextreme-sources
          path: |
            devextreme-installer.tgz
            devextreme-dist-installer.tgz
            devextreme-angular-installer.tgz
            devextreme-react-installer.tgz
            devextreme-vue-installer.tgz
          retention-days: 1
  
  publish-ES:
    runs-on: ubuntu-latest
    needs: [build-devextreme]
    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v3
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: |
          ${{ env.STORE_PATH }}
          .nx/cache
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store

    - name: Install dependencies
      run: |
        corepack enable
        pnpm install

      - name: Download devextreme sources
        uses: actions/download-artifact@v4
        with:
          name: devextreme-sources

        # NOTE: workaround due to wrappers are incorrect pnpm packages now
      - name: Install wrappers packages
        run: |
          rm -rf node_modules/devextreme node_modules/devextreme-dist node_modules/devextreme-angular node_modules/devextreme-react node_modules/devextreme-vue
          mkdir node_modules/devextreme node_modules/devextreme-dist node_modules/devextreme-angular node_modules/devextreme-react node_modules/devextreme-vue
          tar -xzf devextreme-installer.tgz -C node_modules/devextreme
          mv node_modules/devextreme/package/* node_modules/devextreme
          tar -xzf devextreme-dist-installer.tgz -C node_modules/devextreme-dist
          mv node_modules/devextreme-dist/package/* node_modules/devextreme-dist
          tar -xzf devextreme-angular-installer.tgz -C node_modules/devextreme-angular
          mv node_modules/devextreme-angular/package/* node_modules/devextreme-angular
          tar -xzf devextreme-react-installer.tgz -C node_modules/devextreme-react
          mv node_modules/devextreme-react/package/* node_modules/devextreme-react
          tar -xzf devextreme-vue-installer.tgz -C node_modules/devextreme-vue
          mv node_modules/devextreme-vue/package/* node_modules/devextreme-vue

      - name: Prepare configs
        working-directory: apps/demos
        run: pnpm run prepare-js
      
      - name: Copy metadata
        working-directory: apps/demos
        run: pnpm run make-demos-bundle -- --copy-metadata

      - name: Prepare React demo bundles
        working-directory: apps/demos
        run: pnpm run make-demos-bundle -- --framework React

      - name: Prepare Vue demo bundles
        working-directory: apps/demos
        run: pnpm run make-demos-bundle -- --framework Vue

      - name: Save publish-demos directory for ES as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish-demos
          path: ./apps/demos/publish-demos

  publish-angular:
    runs-on: ubuntu-latest
    needs: [build-devextreme]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check generated demos (1/10)
            command: CONSTEL=1/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (2/10)
            command: CONSTEL=2/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (3/10)
            command: CONSTEL=3/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (4/10)
            command: CONSTEL=4/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (5/10)
            command: CONSTEL=5/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (6/10)
            command: CONSTEL=6/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (7/10)
            command: CONSTEL=7/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (8/10)
            command: CONSTEL=8/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (9/10)
            command: CONSTEL=9/10 pnpm run make-demos-bundle -- --framework Angular
          - name: Check generated demos (10/10)
            command: CONSTEL=10/10 pnpm run make-demos-bundle -- --framework Angular
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Download devextreme sources
        uses: actions/download-artifact@v4
        with:
          name: devextreme-sources

        # NOTE: workaround due to wrappers are incorrect pnpm packages now
      - name: Install wrappers packages
        run: |
          rm -rf node_modules/devextreme node_modules/devextreme-dist node_modules/devextreme-angular node_modules/devextreme-react node_modules/devextreme-vue
          mkdir node_modules/devextreme node_modules/devextreme-dist node_modules/devextreme-angular node_modules/devextreme-react node_modules/devextreme-vue
          tar -xzf devextreme-installer.tgz -C node_modules/devextreme
          mv node_modules/devextreme/package/* node_modules/devextreme
          tar -xzf devextreme-dist-installer.tgz -C node_modules/devextreme-dist
          mv node_modules/devextreme-dist/package/* node_modules/devextreme-dist
          tar -xzf devextreme-angular-installer.tgz -C node_modules/devextreme-angular
          mv node_modules/devextreme-angular/package/* node_modules/devextreme-angular
          tar -xzf devextreme-react-installer.tgz -C node_modules/devextreme-react
          mv node_modules/devextreme-react/package/* node_modules/devextreme-react
          tar -xzf devextreme-vue-installer.tgz -C node_modules/devextreme-vue
          mv node_modules/devextreme-vue/package/* node_modules/devextreme-vue

      - name: Prepare configs
        working-directory: apps/demos
        run: pnpm run prepare-js

      - name: Copy metadata
        working-directory: apps/demos
        run: pnpm run make-demos-bundle -- --copy-metadata

      - name: Update angular.json
        working-directory: apps/demos
        run: pnpm run update-angular-json

      - name: Create angular entryPoints to compile faster
        working-directory: apps/demos
        run: pnpm run launch-ngcc

      - name: Prepare Angular demo bundles
        working-directory: apps/demos
        run: |
          ${{ matrix.command }}

      - name: Angular post process index.html
        working-directory: apps/demos
        run: pnpm run post-process-angular
      
      - name: Save publish-demos directory for Angular as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish-demos
          path: ./apps/demos/publish-demos

  deploy:
    runs-on: ubuntu-latest
    needs: [build-devextreme, publish-ES, publish-angular]
    steps: 
      - name: Download publish-demos artifact
        uses: actions/download-artifact@v3
        with:
          name: publish-demos
          path: ./apps/demos/publish-demos
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/demos/publish-demos
