name: TestCafe tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [25_2]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_TOKEN }}
  NX_SKIP_NX_CACHE: ${{ (github.event_name != 'pull_request' || contains( github.event.pull_request.labels.*.name, 'skip-cache')) && 'true' || 'false' }}
  BUILD_TEST_INTERNAL_PACKAGE: true

jobs:
  build:
    name: build

    runs-on: devextreme-shr2
    timeout-minutes: 15

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: |
          ${{ env.STORE_PATH }}
          .nx/cache
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpx nx build devextreme

    - name: Zip artifacts
      working-directory: ./packages/devextreme
      run: |
        7z a -tzip -mx3 -mmt2 artifacts.zip artifacts ../devextreme-scss/scss/bundles

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: devextreme-artifacts
        path: ./packages/devextreme/artifacts.zip
        retention-days: 1

  testcafe:
    name: ${{ matrix.ARGS.name }}${{ (matrix.ARGS.theme == null || matrix.ARGS.theme == '') && ' - fluent' || '' }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        ARGS: [
          { componentFolder: "accessibility", name: "accessibility (1/2)", indices: "1/2" },
          { componentFolder: "accessibility", name: "accessibility (2/2)", indices: "2/2" },
          { componentFolder: "common", name: "common" },
          { componentFolder: "treeList", name: "treeList", concurrency: 1 },
          { componentFolder: "dataGrid/common", name: "dataGrid / common (1/5)", indices: "1/5" },
          { componentFolder: "dataGrid/common", name: "dataGrid / common (2/5)", indices: "2/5" },
          { componentFolder: "dataGrid/common", name: "dataGrid / common (3/5)", indices: "3/5" },
          { componentFolder: "dataGrid/common", name: "dataGrid / common (4/5)", indices: "4/5" },
          { componentFolder: "dataGrid/common", name: "dataGrid / common (5/5)", indices: "5/5" },
          { componentFolder: "dataGrid/sticky/common", name: "dataGrid / sticky common" },
          { componentFolder: "dataGrid/sticky/fixed", name: "dataGrid / sticky (1/3)", indices: "1/3" },
          { componentFolder: "dataGrid/sticky/fixed", name: "dataGrid / sticky (2/3)", indices: "2/3" },
          { componentFolder: "dataGrid/sticky/fixed", name: "dataGrid / sticky (3/3)", indices: "3/3" },
          { componentFolder: "cardView", name: "cardView" },
          { componentFolder: "pivotGrid", name: "pivotGrid", concurrency: 1 },
          { componentFolder: "scheduler/common", name: "scheduler / common (1/6)", indices: "1/6" },
          { componentFolder: "scheduler/common", name: "scheduler / common (2/6)", indices: "2/6" },
          { componentFolder: "scheduler/common", name: "scheduler / common (3/6)", indices: "3/6" },
          { componentFolder: "scheduler/common", name: "scheduler / common (4/6)", indices: "4/6" },
          { componentFolder: "scheduler/common", name: "scheduler / common (5/6)", indices: "5/6" },
          { componentFolder: "scheduler/common", name: "scheduler / common (6/6)", indices: "6/6" },
          { componentFolder: "scheduler/viewOffset/common", name: "scheduler / offset" },
          { componentFolder: "scheduler/viewOffset/markup", name: "scheduler / offset markups" },
          { componentFolder: "scheduler/timezones", name: "scheduler / timezones (Europe/Berlin)", timezone: "Europe/Berlin" },
          { componentFolder: "scheduler/timezones", name: "scheduler / timezones (America/Los_Angeles)", timezone: "America/Los_Angeles" },
          { componentFolder: "editors", name: "editors (1/4)", indices: "1/4" },
          { componentFolder: "editors", name: "editors (2/4)", indices: "2/4" },
          { componentFolder: "editors", name: "editors (3/4)", indices: "3/4" },
          { componentFolder: "editors", name: "editors (4/4)", indices: "4/4" },
          { componentFolder: "navigation", name: "navigation" },
          { componentFolder: "filterBuilder", name: "filterBuilder" },
          { componentFolder: "pagination", name: "pagination" },
          { componentFolder: "gantt", name: "gantt" },
        ]
    runs-on: devextreme-shr2
    timeout-minutes: 45

    steps:
    - name: Set machine timezone
      run: |
        sudo ln -sf "/usr/share/zoneinfo/$([ "${{ matrix.ARGS.timezone }}" != "" ] && echo "${{ matrix.ARGS.timezone }}" || echo "GMT")" /etc/localtime
        date

    - name: Get sources
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: devextreme-artifacts
        path: ./packages/devextreme

    - name: Unpack artifacts
      working-directory: ./packages/devextreme
      run: 7z x artifacts.zip -aoa

    - name: Setup Chrome
      uses: ./.github/actions/setup-chrome
      with:
        chrome-version: '133.0.6943.53'

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: |
          ${{ env.STORE_PATH }}
          .nx/cache
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run TestCafe tests
      working-directory: ./e2e/testcafe-devextreme
      run: |
        if [ "${{ matrix.ARGS.theme }}" != "" ]; then
          THEME="--theme ${{ matrix.ARGS.theme }}"
        else
          THEME="--theme fluent.blue.light"
        fi
        [ "${{ matrix.ARGS.indices }}" != "" ] && INDICES="--indices ${{ matrix.ARGS.indices }}"
        [ "${{ matrix.ARGS.concurrency }}" != "" ] && CONCURRENCY="--concurrency ${{ matrix.ARGS.concurrency }}"
        [ "${{ matrix.ARGS.platform }}" != "" ] && PLATFORM="--platform ${{ matrix.ARGS.platform }}"
        all_args="--browsers=chrome:devextreme-shr2 --componentFolder ${{ matrix.ARGS.componentFolder }} $CONCURRENCY $INDICES $PLATFORM $THEME"
        echo "$all_args"
        pnpm run test $all_args

    - name: Sanitize job name
      if: ${{ failure() }}
      run: echo "JOB_NAME=$(echo "${{ matrix.ARGS.name }}" | tr '/' '-')" >> $GITHUB_ENV

    - name: Copy compared screenshot artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: compared-screenshots-${{ env.JOB_NAME }}
        path: ${{ github.workspace }}/e2e/testcafe-devextreme/artifacts/compared-screenshots/**/*
        if-no-files-found: ignore

    - name: Copy failed test artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: failed-tests-${{ env.JOB_NAME }}
        path: ${{ github.workspace }}/e2e/testcafe-devextreme/artifacts/failedtests/**/*
        if-no-files-found: ignore

  merge-artifacts:
    runs-on: devextreme-shr2
    needs: testcafe
    if: ${{ failure() }}

    steps:
    - name: Merge screenshot artifacts
      uses: actions/upload-artifact/merge@v4
      continue-on-error: true
      with:
        name: compared-screenshots
        pattern: compared-screenshots-*
        delete-merged: true

    - name: Merge failed test artifacts
      uses: actions/upload-artifact/merge@v4
      continue-on-error: true
      with:
        name: failed-tests
        pattern: failed-tests-*
        delete-merged: true

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [build, testcafe]
    if: github.event_name != 'pull_request' && contains(needs.*.result, 'failure')

    steps:
      - uses: actions/checkout@v4
      - uses: DevExpress/github-actions/send-teams-notification@v1
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
