name: Test publishing to GitHub Packages

on:
  push:
    branches: [revert/migrate-angular-to-nx]
env:
  NX_SKIP_NX_CACHE: true

jobs:
  build:
    name: Build packages
    runs-on: windows-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.PNPM_STORE_PATH }}
            .nx/cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set timestamp version
        if: ${{ env.SET_TIMESTAMP_VERSION == 'true' }}
        run: pnpx ts-node tools/scripts/set-timestamp-version

      - name: Build npm packages
        env:
          BUILD_INTERNAL_PACKAGE: true
        run: pnpm run all:build
